### ISSUE TITLE
Automatic alerts for server responsiveness.

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#103]
See https://github.com/HaxeFoundation/haxe/issues/3919#issuecomment-76138660

I personally use Rackspace hosting and they have an integrated uptime monitoring service.  So I'm not familiar with what else is on the market.

I know there's services like https://www.pingdom.com/pricing/ but not sure what else exists on the market.  Any recommendations?

Or we could do a simple hand-made test and just run it on a cronjob from someone elses hosting.  I could volunteer my VPS.

**Comment by Simn** [comment]
#138
