### ISSUE TITLE
API docs automation

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#104]
see https://github.com/HaxeFoundation/haxe.org/issues/41#issuecomment-76520858

Not a 3.2 priority, but having it shortly after that would be awesome!

**Comment by ncannasse** [comment]
@jasononeil up ?

**Comment by Simn** [comment]
I would like to see this addressed with priority because updating this by hand is really obnoxious.

**Comment by ncannasse** [comment]
Another up to @jasononeil :)

**Comment by andyli** [comment]
Done. The TravisCI builds from the development branch of the haxe repo will deploy api docs to http://api.haxe.org/v/dev/.

**Comment by Simn** [comment]
THANK YOU!

I'm reopening as a reminder to generate the 3.2.1 documentation again. There's also still the issue of versioning these, e.g. v/3.2.1/. I'm not sure how much of that we want to automate too.

**Comment by andyli** [comment]
I am considering to deploy the release versions by using the Travis builds of tagged commits. I will look into that : )

**Comment by Simn** [comment]
That would be perfect!

The last thing is that we have to deploy the content of api.haxe.org itself. This should always be the latest release version. I'm not sure if we have to semver compare that because there could be something like 3.0_bugfix again which when tagged shouldn't overwrite the current documentation.

**Comment by markknol** [comment]
@andyli Hey man, this is encouraging news!

**Comment by markknol** [comment]
Does this use a git version of dox?

**Comment by andyli** [comment]
@Simn 

I'm not sure if I understand what you mean. Here is what I'm going to implement:

Case 1: when there is an existing tag, say 4.0.0, and we want to re-tag it to another commit. We should overwrite the old 4.0.0 docs.
Case 2: when there is an existing tag, say 4.0.0, and we want to create a new bug-fix release, 4.0.1. It should create a new set of docs (4.0.1), and leave the 4.0.0 one unmodified.

The default docs accessible from the root of api.haxe.org should always point to the latest release (no beta) according to semver.

The dev docs accessible from /v/dev should always be deployed from the development branch. Rebuild of old-commit should not overwrite existing one.

Let me know if I missed anything.

**Comment by andyli** [comment]
@markknol Yes, it is using git versions. We're using `make install_dox` in https://github.com/HaxeFoundation/haxe/blob/development/Makefile#L210

**Comment by Simn** [comment]
> The default docs accessible from the root of api.haxe.org should always point to the latest release (no beta) according to semver.

This is what I meant.
