### ISSUE TITLE
Include Proletariat Logos 

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/haxe.org#106]
Hi there,

Here are two Logo Versions from our new partner, Proletariat, Inc.

Would you mind including them with the current partner logos?

Thanks!
![proletariatlogo_banner](https://cloud.githubusercontent.com/assets/5541210/6445453/425b4c06-c104-11e4-9423-f4a923bdf819.png)
![proletariatlogo_onlyp_red](https://cloud.githubusercontent.com/assets/5541210/6445452/425b41a2-c104-11e4-9386-08914d525c14.png)

**Comment by Simn** [comment]
One of them that is.

**Comment by Merelleya** [comment]
It should go in the "supporters" section.

**Comment by Simn** [comment]
@jasononeil: Could you add this soon?
