### ISSUE TITLE
Travis haxe 3.2.0-rc.2

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe.org#119]
Follows https://github.com/travis-ci/travis-ci/issues/3650

For travis support to work the files must be in `http://haxe.org/website-content/downloads/{version}/downloads/haxe-{version}-linux64.tar.gz`.

Currently for haxe 3.2.0-rc.2 the folder version is: `3,2,0-rc,2`
but the file version is `3.2.0-rc2` (one has a dot but not the other).

**Comment by Simn** [comment]
@jasononeil: Could we hack-fix this in some way that doesn't require duplicating the binaries?

**Comment by andyli** [comment]
related issue: #111

**Comment by andyli** [comment]
In the time being @ibilon you may use "haxe:development" instead.

**Comment by 7-by** [comment]
What about add possibility to set url to haxe build instead version? this fix also will help when i want use custom haxe bin (for example not latest, but after some commit to haxe repo http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/linux64/haxe_2015-04-14_development_7bc43d8.tar.gz)

**Comment by andyli** [comment]
I'm not sure about custom url. But supporting to test a specific commit sounds useful.
Maybe something like this?
```
haxe:
  - development@7bc43d8
```

**Comment by 7-by** [comment]
hm, case with url will be better, because dev's could use not only official build from haxe foundation repo, for example https://github.com/pleclech/hacking-haxe

**Comment by andyli** [comment]
I'm not sure. It is kind of encouraging forks, which I personally don't want to.
If such level of customizability is needed, you may simply build or download your version of haxe in the `before_install` section.

**Comment by 7-by** [comment]
When i add `before_install` section with downloading haxe binaries and remove section `haxe:` then travis download haxe 3.1.3 by default and install it and after that i need remove it and download, install custom haxe bin again in section `before_install`. I think it's wrong way

**Comment by andyli** [comment]
Well, of course if you want to install custom version of haxe, you wouldn't be using `language: haxe`, but `language: generic` or whatever language you're targeting. ;)

**Comment by andyli** [comment]
And even if you're using `language: haxe`, I believe you don't have to remove the travis-installed haxe. Just make sure the PATH variable is properly configured such that the system would reach your version first.

**Comment by 7-by** [comment]
argh, you right! Then i can't use `hxml` and other stuffs related for haxe language. It will need describe all this data into `.yml`, but if i use `hxml` for compilation then i will have it in two places (one `.yml` and second is 'hxml')

**Comment by andyli** [comment]
It isn't that hard :)

```yaml
language: haxe
hxml: build.hxml
before_install:
 - ./download_custom_haxe.sh
 - export PATH=path/to/custom_haxe:$PATH 
```

or:
```yaml
language: generic
install:
 - ./install_custom_haxe.sh
 - haxelib install build.hxml
script:
 - haxe build.hxml
```

**Comment by 7-by** [comment]
agree with second code listing. In first listing travis install haxe twice

**Comment by ibilon** [comment]
@andyli Development version of haxe works,
but it looks like they aren't bundled with a development version of haxelib
so lime doesn't install and since selfupdate fails on linux I'm stuck again

**Comment by andyli** [comment]
@ibilon 
The development build bundle the haxelib version of the submodule reference.
So it is not really a TravisCI problem, but a haxelib problem...
Has the Lime installation problem been reported to haxelib yet?

**Comment by ibilon** [comment]
@andyli 
Reported and even fixed in the 3.2.0-rc.3 version of haxelib,
so I guess it's just a matter of updating the submodule.

**Comment by andyli** [comment]
Alright!

@back2dos Could we update the submodule? The latest haxelib source should be less broken than the submodule one, right?

**Comment by back2dos** [comment]
Yes, you can go ahead. It might be best to use [3.2.0-rc.3](https://github.com/HaxeFoundation/haxelib/releases/tag/3.2.0-rc.3). There have been some relatively extensive contributions after that, which I'd rather release *after* the final Haxe 3.2.0 release.

**Comment by Simn** [comment]
What about that shim stuff?

**Comment by andyli** [comment]
@ibilon I have updated the submodule. Would you trigger a rebuild and see if it work?

**Comment by ibilon** [comment]
@andyli fixed it, thanks

**Comment by Simn** [comment]
Does this break if I use rc.1 next time?

**Comment by jasononeil** [comment]
@Simn I thought about that after I pushed this. I'm working on another commit at the moment where I will standardize the naming of all binaries to match the version number in the folder.  If we can stick to that rule going forward it'll be fine. Stay tuned...

**Comment by jasononeil** [comment]
@Simn, what I've done now is renamed all the folders to use a period ("1.0.0") instead of a comma ("1,0,0"), and then made sure all the binaries have a version number identical.

I've provided redirects for the old paths, so it shouldn't break any old scripts etc.

For future releases, we just need to make sure the download files have a version number identical to the folder number.  (I think having "3.3.0-rc.1" is preferable to "3.3.0-rc", but both will still work as long as you are consistent).
