### ISSUE TITLE
Base64 returns different results

### ISSUE THREAD

**Issue by LordCorax** [HaxeFoundation/haxe.org#123]
It seems that there is a bug in haxe.crypto.Base64.
I used Base64's decode method to convert a simple string into a byte-object.
After that I called the encode method to get my original string value back.

But that didn't work out properly. Instead of friendly "Hello" I got a "Hell" in my output panel.
So what the hell is actually going on? ;-)

Btw the code:

```
public function new() 
{
	super();
	var bytes:haxe.io.Bytes = haxe.crypto.Base64.decode("Hello");
	Lib.trace(bytes.toString());
	Lib.trace(haxe.crypto.Base64.encode(bytes));
}
```

Result:

```
Lib.hx:145: ée
Lib.hx:145: Hell
```

**Comment by Simn** [comment]
This repository is for the haxe.org website, try the haxe one for compiler issue reports.

**Comment by markknol** [comment]
BTW, your example is incorrect and should be:
```haxe
var bytes = haxe.crypto.Base64.encode(haxe.io.Bytes.ofString("Hello"));
trace(bytes.toString()); // SGVsbG8=
trace(haxe.crypto.Base64.decode(bytes)); // hello
```
