### ISSUE TITLE
ExprDef is missing from the new Docs

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe.org#126]
Compare http://api.haxe.org/v/dev/haxe/macro/Expr.html with http://api.haxe.org/haxe/macro/Expr.html

In the second one you can click on ExprDef but not in the first.  I suspect there are other things missing as well.

**Comment by Simn** [comment]
I have already fixed this, will update v/dev a bit later.

**Comment by Simn** [comment]
done
