### ISSUE TITLE
haxe.org slowdown

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#128]
I noticed quite a slowdown on haxe.org today, the server was ok but apache was flooded with requests, here's the status dump:

http://haxe.org/server-status.html

Any idea ? DDOS ?

**Comment by jasononeil** [comment]
I had noticed that tora is still memory leaking, though this time the breakdown of memory in each of the websites is not giving any clues.  Next time I notice it I will take a log so you can look at it.

That seems separate from this though.  Most of the requests on that status page seem to be from the dokuwiki indexer.  I'm not familiar enough with dokuwiki to know what is "normal", but if the installation is old, it might be vulnerable to security attacks...

**Comment by ncannasse** [comment]
It is very old, maybe we should replace the nekovm website with a haxe solution, if you're up to the task ?

**Comment by jasononeil** [comment]
We could mostly re-use the technology from the Haxe website but use different content / templates.  Should we discuss it further this weekend?

**Comment by ncannasse** [comment]
Sure :)

**Comment by Simn** [comment]
Is this resolved?

**Comment by ncannasse** [comment]
Yes, Neko.org was moved to better tech :)

**Comment by markknol** [comment]
What is the status of the new nekovm site?

**Comment by ncannasse** [comment]
We don't have much to change, it's been rewritten using markdown here https://github.com/HaxeFoundation/nekovm.org

**Comment by markknol** [comment]
Is that version currently online?

**Comment by ncannasse** [comment]
Yes I think so
