### ISSUE TITLE
Downtime alerts?

### ISSUE THREAD

**Issue by aduros** [HaxeFoundation/haxe.org#138]
haxe.org has been pretty slow/unreachable over the past few weeks, sometimes for a decent stretch of time. Are we using any monitoring services (pingdom, uptime robot, etc) to tell when the server needs a hug?

**Comment by ncannasse** [comment]
first we had issues with new haxe.org due to a leak in minject, which was fixed. it seems now there's a issue with new haxelib website, I've limited tora memory so it will not take all of it and start swapping, hope it works as a patch until fixed

**Comment by ncannasse** [comment]
But yes, we should setup an alert system, any suggestion @jasononeil ?

**Comment by Merelleya** [comment]
I have asked @jasononeil to look into possible options. We looked at pingdom and he will take a short look around at other options just to compare.

**Comment by Simn** [comment]
What's the state of this? The website has been stable recently, but it would still be nice to have some sort of alert.

**Comment by Simn** [comment]
I'll go ahead and close this because we don't seem to have any issues anymore and nobody feels responsible anyway.
