### ISSUE TITLE
Take off Basis from the list of frameworks for iOS/Android

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe.org#139]
Basis*[0] is listed in the official Haxe website as a feasible framework for building apps for iOS/Android. The problem is that the library doesn't seem to be maintained as of late (last commit is from 2013). If it's not currently supported, we should take it off the list, at least until someone can make sure it really works as of now.

As a related note, @Randonee mentioned this, regarding Basis, in a mailing list post from today:

```
I probably won't continue work on BasisApple because I don't see it as a good solution. However, if a swift target were created or a good interface to cocoa I would update Basis to generate whatever project files would be needed for it.

Aaron
```

Now this is a simple change and I can put a PR up, but wanted to touch base with everyone else first.

[0] https://github.com/Randonee/Basis

See the original issue here: https://github.com/HaxeFoundation/Project-Management/issues/32#issuecomment-110884400

**Comment by Simn** [comment]
Why is this not a pull request? ;)

**Comment by fullofcaffeine** [comment]
There you go! https://github.com/HaxeFoundation/haxe.org/pull/140
