### ISSUE TITLE
Link to lib.haxe.org

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe.org#141]
If there is any link in the navigation or footer, I haven't found it / it's well hidden. All the free libs Haxe has should be advertised as a feature.

**Comment by markknol** [comment]
:boom: 1000 free libs, click here to download :boom:

**Comment by ncannasse** [comment]
I agree we need to have haxelib in our top menu navigation. The question is where exactly ?

**Comment by Simn** [comment]
I thought that if we go for https://github.com/HaxeFoundation/haxe.org/issues/105#issuecomment-110930894 we could make the subdomain part clickable and have a dropdown like for other menu items.

**Comment by markknol** [comment]
Yes, that's a good plan!

**Comment by ncannasse** [comment]
@Simn maybe, but I wonder if people will understand that it's clickable :) It doesn't look much like a menu at first glance

**Comment by Simn** [comment]
We could add a small triangle pointing down at the bottom right of the "button".

However, we should also feature lib.haxe.org on the body of the entry page. On that note, did I mention that there's WAY TOO MUCH TEXT THERE? :D

**Comment by markknol** [comment]
It could be structured in a more visual attractive matter.

**Comment by ibilon** [comment]
Let's merge this issue with #245
