### ISSUE TITLE
api.haxe.org search

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#143]
Currently when searching on api.haxe.org, if you happen to write a package name (for instance "Reflect") you'll have all the classes from that package listed.

I suggest instead we only link the package, so for instance a search for `reflect` would list:

```
Reflect
cs.system.reflection
java.lang.reflect
```

Please note that it would be nice to prioritize in the results the toplevel and haxe/sys packages against the platform-specific packages. so for instance `http` search would list the `haxe.Http` class first.

**Comment by ncannasse** [comment]
Also, the current search will only perform a local/client search based on the types index. If we want to search into the full documentation, we should either roll out a full search tech or add a link to this `https://www.google.com/?#q=site:api.haxe.org+trim` at the bottom of the search results (with a "all results" caption ?)

**Comment by Simn** [comment]
Search should be Filter. We changed that before but apparently it got changed back with the theme change.

Prioritizing results is not going to work via CSS tricks I think, so this would require something more elaborate. Maybe just use google search like on the main site?

**Comment by Simn** [comment]
The search has been improved a lot as you can see on /v/dev. I don't plan to add package-search at the moment. I also don't want to mix up the type filter and a full-text search, so if anything that should be addressed from a separate search box like on haxe.org.

**Comment by ncannasse** [comment]
Please note that if you filter by platform (for instance "neko"), the other platforms packages still appear in the search

**Comment by ibilon** [comment]
That's a dox issue.
