### ISSUE TITLE
Latest windows nightlies missing

### ISSUE THREAD

**Issue by azrafe7** [HaxeFoundation/haxe.org#146]
It seems that since august 26 the windows nightlies from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows/ aren't being built.

**Comment by azrafe7** [comment]
Also, latest windows installers from http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/windows-installer/ are corrupt/wrong size.

**Comment by andyli** [comment]
ping @waneck ;)

**Comment by waneck** [comment]
I'll work on it today

**Comment by waneck** [comment]
It should be working now

**Comment by azrafe7** [comment]
It works, thanks!

Just noticed that the [sources](http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/source/) folder seems to suffer from the same problem.
