### ISSUE TITLE
ufront build error

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#151]
Since a today I suddenly have this error:

![image](https://cloud.githubusercontent.com/assets/576184/10418825/f8f17736-7065-11e5-8e5e-edbfda97ca39.png)

Very strange, I want to add new stuff to the branding page but now it doesn't work locally anymore. Anyone can help on this?

**Comment by markknol** [comment]
Also, if i just run `ufront server` I see this:

![image](https://cloud.githubusercontent.com/assets/576184/10418858/92ed5954-7066-11e5-9608-0c4429466faf.png)

But got this in the browser:
![image](https://cloud.githubusercontent.com/assets/576184/10418843/6f0923a6-7066-11e5-83c8-f57b1cb4b1df.png)

**Comment by markknol** [comment]
Since it is all ufront this might be related to https://github.com/HaxeFoundation/nekovm.org/issues/3 too..

**Comment by kevinresol** [comment]
Try installing `minject` of version "2.0.0-rc.1"?

**Comment by kevinresol** [comment]
It is a bit hard to get started with the ufront lib actually. I think it is due to its many dependencies.

I found that the best way to get ufront working is to git clone the ufront/ufront repo. Then run the ./setupDev script

**Comment by Simn** [comment]
@jasononeil: Can we sort out dependency versions once and for all and then try to keep everything compatible?

**Comment by markknol** [comment]
@andyli @Simn I tried to get the site working again but still i don't get it up and running. Any hint?

I did `ufront build` and this appeared:
```
Build basicclient.hxml
Build clientapp.hxml
src/app/Routes.hx:6: characters 7-24 : Type not found : ufblog.BlogRoutes
src/Client.hx:5: lines 5-26 : Defined in this class
Build serverapp.hxml
src/app/Routes.hx:6: characters 7-24 : Type not found : ufblog.BlogRoutes
src/Server.hx:5: lines 5-47 : Defined in this class
src/Server.hx:40: characters 20-42 : Unknown identifier : BlogRemotingApiContext

src/app/Config.hx:11: characters 26-72 : Failed to load file conf/mysql.json: Fi
le not found 'conf/mysql.json'
Failed to build clientapp.hxml, serverapp.hxml
```

**Comment by andyli** [comment]
There are submodule changes, so you have to `git submodule init && git submodule update`.

**Comment by markknol** [comment]
I did what you said, now it has different errors. It seems the closure compiler outputs everything in the console, but I also have this error: 

```
Build serverapp.hxml
src/app/Config.hx:11: characters 26-72 : Failed to load file conf/mysql.json: File not found 'conf/mysql.json'
Failed to build serverapp.hxml
```
Which is true, because I cannot find the _mysql.json_ in the project too.

**Comment by kevinresol** [comment]
@markknol probably because the json contains credentials so Jason didn't commit it to the repo

**Comment by kevinresol** [comment]
btw, it should look something like this:
```haxe
{
 	"host":"localhost",
 	"user":"ufhelloworld",
 	"pass":"ufhelloworld",
 	"port":3306,
 	"socket":null,
 	"database":"ufhelloworld"
 } 
```

**Comment by markknol** [comment]
Ok, thanks! It now compiles and I can start the `ufront server`, but I see this in the browser:
```
Called from tools/WebServer.nml line 501
Called from tools/WebServer.nml line 473
Called from neko/imagemagick/Imagick.hx line 1475
Called from tools/WebServer.nml line 484
Exception : Neko_error(load.c(237) : Failed to load library : nMagick.ndll)
```

**Comment by kevinresol** [comment]
That's a runtime dependecy thing. Maybe you should find the nMagick.ndll somewhere...

**Comment by andyli** [comment]
"nMagick.ndll" is provided in the [ImageMagick haxelib](https://bitbucket.org/yar3333/haxe-imagemagick). However, it provides Windows and Linux ndlls only... I've successfully compiled a Mac ndll and will see if I can send a PR to get it bundled.

**Comment by andyli** [comment]
I've pushed my Mac ndll to https://bitbucket.org/andyli/haxe-imagemagick. Would you check if it work on your machine? I'm not very sure whether it is portable since I'm using the homebrew-installed neko, which places libneko at location different from the official installer. And you have to `brew install imagemagick` to get "libMagickWand-6.Q16.2.dylib" for the ndll to load too.

**Comment by Simn** [comment]
I'm having trouble with this as well (on Windows). Even putting the file in the same directory I'm running the server at gives me "Exception : Neko_error(load.c(237) : Failed to load library : ./nMagick.ndll)".

I didn't look into rebuilding that thing myself yet, nor do I particularly want to...

**Comment by Simn** [comment]
Apparently my problem was that I had the 64bit version of ImageMagick and needed the 32bit one.

**Comment by ibilon** [comment]
Yeah that's not the easiest project to get started with,
for me it was (now fully working): nMagick.ndll for linux64 wasn't link to the right lib
the database was empty and I had to create rows manually (figuring out what to put in some fields wasn't easy)
and last but not least nekotools server randomly dropping the __x param of remoting call
configuring apache is a pain also

Anyone else had issue with the db? Maybe we should add a sample sql file to populate it.

**Comment by Simn** [comment]
Did you do this step? "Visit http://localhost:2987/blog/ufadmin/ and click on "DB Admin" to create and sync each of the required tables."

**Comment by ibilon** [comment]
Yeah, the tables were here, but empty.

**Comment by ibilon** [comment]
Not an issue anymore.
