### ISSUE TITLE
Unable to compile with the .NET 4.5 framework

### ISSUE THREAD

**Issue by joel-arthur** [HaxeFoundation/haxe.org#152]
When trying to compile with .NET 4.5,

adding
-net-lib C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.5\mscorlib.dll

Or

Including Mono's .NET 4.5 dlls with:
-D net-ver=45

results in the following error:
PeReader.Error_message("Error reading compressed data. Invalid first byte: e5")
Build halted with errors (haxe.exe).

I have also seen this error:

File "ilMetaReader.ml", line 577, characters 34-40: Assertion failed
error 0x2

trying to set -net-std to "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5"

**Comment by Simn** [comment]
Please report at https://github.com/HaxeFoundation/haxe/issues
