### ISSUE TITLE
OpenSuse package issues

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe.org#157]
Hi,

I had no idea where to put this issue so hopefully this isn't too weird here,
this is more for @andyli I guess.

Tried the opensuse's rpm for haxe and neko,
the install worked great, tested all haxe target with a hello world without issue,
and the install was quicker/easier than doing it by hand. Thanks!

You should activated it for the latest version (leap 42.1).

But then I tried openfl and run into this issue:
```
Could not link to neko.
Could not link plugin to process (CFFILoader.h 202) - with neko
```
tracking it in hxcpp's code I found that it's because the rpm installs `libneko.so.1` and hxcpp looks for `libneko.so` or then `libneko.so.0`.
A symbolic link fixed that.

Also had to make a link for `libpcre.so.3` (to `libpcre.so.1`) which doesn't exist,
checked on my 13.1 the link is also there but I don't remember if I did it or the os.

**Comment by andyli** [comment]
Thanks for reporting!

All openSUSE versions including Leap 42.1 should have been enabled. It should be in the list in the right column at https://build.opensuse.org/project/show/devel:languages:haxe

For .so, I will make a PR to hxcpp.

**Comment by ibilon** [comment]
Indeed it was, not sure why I thought it wasn't.

I double check on the libpcre, the rpm lists `libpcre.so.1()(64bit)` as a dependency and all the ndll link against it too.
So no idea why it was complaining about `libpcre3`, I'll have to install another opensuse 42 soon so unless it complains there too I'll assume it was something else.

**Comment by Simn** [comment]
Is this resolved?

**Comment by ibilon** [comment]
`libneko1` now installs a `libneko.so.0`

Made a test on a clean vm and all worked, thanks.
