### ISSUE TITLE
Page not found and debug informations

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe.org#161]
When accessing a page that doesn't exist you get a "Page Not Found" as expected,

but the title is "Error: Page Not Found app.api.PageApi.locatePage:41"
and the console logs `app.api.PageApi.locatePage(40): Could not find page /data/newhaxe/www/website-content/pages/doc/videos/editors/Intelij/index.[html,md]` and `ufront.handler.ErrorPageHandler.handleError(53): Handling error: Error: Page Not Found app.api.PageApi.locatePage:41`

which looks like debug information that shouldn't be on the production website.

Also it doesn't have the same footer as all the other pages (and is copyrighted in 2013 instead of 2015).

**Comment by Simn** [comment]
Is it really a problem to hit the console with some debug information? Yes production and all that, but we're talking about the browser console here.

**Comment by ibilon** [comment]
Yeah, mostly about showing the path on the server,

but the title of the page isn't hidden information and should really juste be "Page not found".

**Comment by Simn** [comment]
Oh, I didn't even notice the title. I agree that should be changed.

**Comment by ibilon** [comment]
Can't figure out how, but that's fixed.
