### ISSUE TITLE
Duplicate <title> in the manual

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#162]
For instance:

http://haxe.org/manual/lf-static-extension.html
http://haxe.org/manual/macro-limitations-static-extension.html

```html
<title>Static extension - Haxe - The Cross-platform Toolkit</title>
```

While I could fix this in the manual itself, I would prefer if we generated titles similar to how wikipedia deals with disambiguity:

Static Extensions (Language Features) - Haxe - The Cross-platform Toolkit
Static Extensions (Macros - Limitations) - Haxe - The Cross-platform Toolkit

**Comment by ibilon** [comment]
Now deployed:
http://staging.haxe.org/manual/lf-static-extension.html
http://staging.haxe.org/manual/macro-limitations-static-extension.html

**Comment by Simn** [comment]
Perfect, thanks a lot!
