### ISSUE TITLE
Partners Logo

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#164]
Urgent update for partners list on homepage and http://haxe.org/foundation page:

As part of the "supporters", add the ChameleonJohn logo 
http://www.chameleonjohn.com
Logo available here http://imgur.com/NwMLiv4

While we update the list we can also remove KnowledgePlayers, which haven't renewed their membership.

Putting it on @andyli top priority list

**Comment by fullofcaffeine** [comment]
I know the issue is closed, but I just saw this partner and I'm curious about how they're using Haxe, that's not mentioned anywhere. It looks like they're doing web with Haxe, is that it?

**Comment by ncannasse** [comment]
Yes, they were supposed to send me some details about it but I didn't get any. I'll ping them back.

**Comment by fullofcaffeine** [comment]
Awesome, @andyli don't forget to put the logo here too: http://haxe.org/use-cases/who-uses-haxe.html
