### ISSUE TITLE
New blog section enhancements

### ISSUE THREAD

**Issue by bablukid** [HaxeFoundation/haxe.org#165]
Hi, thanks a lot for the brand new HF blog !

some basic suggestions : 
- [x] there is no link to the blog in the nav bar (!!?)
- [x] last headlines from the blog in the homepage would be nice 
- [x] the blog has no RSS feed, i'm so sad I can't add it to my Feedly

**Comment by Merelleya** [comment]
It is not linked yet because it is as of yet not properly "released".

there are some more improvements coming up. I will put the RSS feed thing on the list. Unfortunately, we don't have that much WebDev power at the moment, so it will take some time for new things to be added, so bear with us.

**Comment by bablukid** [comment]
sure, thanks for the answer

**Comment by ibilon** [comment]
The first was done,
and I made a rss feed http://staging.haxe.org/blog/rss/

I put a `<link>` tag in the middle of the page so that's not optimal, I'll have to see how to inject in the head, and it could probably use a visible link/rss icon linking to it.

**Comment by Merelleya** [comment]
Thank you so much for doing this!



Am 04/03/2016 um 19:59 schrieb Valentin Lemière:

**Comment by markknol** [comment]
I think this can be closed for now. Thanks!
