### ISSUE TITLE
haxe.org vs. Haxe 3.3

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#166]
We currently have several issues with several libraries:
1. detox: Requires a fix for constant patterns: https://github.com/Simn/detox/commit/a20b5b88895a4a6dfb8bac672efa5d347f8de0f7
2. ufront-mvc: Requires fix for missing Void-match: https://github.com/Simn/ufront-mvc/commit/2a3256219dde5248b3575282628e8178e3f1d07a. The compile-time error is new, but this probably lead to problems before.
3. haxe: There's some regression going on with type loading that leads to ufront failing in obscure ways. This is probably very related to https://github.com/HaxeFoundation/haxe/issues/4825

**Comment by Simn** [comment]
The Haxe issue has been resolved. Now the question is what is gonna happen with @jasononeil's libraries maintenance-wise.

**Comment by Simn** [comment]
Running it locally I get these errors when trying to make a blog post:

```
app.min.js:225 Uncaught TypeError: (intermediate value)(...) is not a function(anonymous function) @ app.min.js:225
new:227 Uncaught ReferenceError: ufExecuteSerializedAction is not defined(anonymous function) @ new:227
VM437:1 Uncaught ReferenceError: ufExecuteAction is not defined(anonymous function) @ VM437:1
```

That almost looks like some DCE problem but haxe.org doesn't use full DCE as far as I can tell.

**Comment by ibilon** [comment]
No but it runs through google closure which does dce,
do you have the same problem if you switch to `client.js` and `app.js` in https://github.com/HaxeFoundation/haxe.org/blob/staging/www/view/layout.html#L109-L110?

**Comment by Simn** [comment]
Alright, Jason has given me access to ufront so if we still need anything there let me know. The 3 original issues have been addressed, I'll check out the DCE (?) problem again before the RC release unless someone else wants to investigate it.

**Comment by ibilon** [comment]
detox needs a new fix for 3.3 https://github.com/ufront/detox/pull/43

Also haxe doesn't ship jquery anymore, so detox can't include it https://github.com/ibilon/detox/blob/master/src/dtx/Tools.hx#L343 so which project should include it?
Also I checked and haxe 3.2.1 included jquery 1.6.1 which is old, what version does haxe extern uses? @andyli

**Comment by markknol** [comment]
Why is a macro needed to include jquery?

We already include Haxe here: 
https://github.com/HaxeFoundation/haxe.org/blob/staging/www/js/jquery.min.js
http://haxe.org/js/jquery.min.js

**Comment by ibilon** [comment]
It's the detox lib that requires it and choose to include it rather than asking the user to do it.

**Comment by jasononeil** [comment]
@markknol @ibilon Is there anything specific you need from me? I hadn't been following this issue but happy to help with a patch, library release, adding you guys as contributors etc

**Comment by markknol** [comment]
@jasononeil it would be great it if you help us out with this! Im not very into the ufront part of the site so if you could check Simons issues that would be awesome!
(Btw good to see activity from you, hope you're good!)

**Comment by ibilon** [comment]
Not an issue anymore.

And actually the new core requires haxe dev for now until https://github.com/HaxeFoundation/haxe/commit/7aba7abe74190704e92b4af3a0b51fb55491abd9 makes it into a release.
