### ISSUE TITLE
Add The Blog to the Navigation

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/haxe.org#170]
@markknol or @andyli 

could one of you find a nice spot to link the blog in the main navigation sow e can go "visible"?

I know the nav is being reworked but in the meantime just put it somewhere people can find it.

Thanks!

**Comment by ibilon** [comment]
I tried it,

there's not enough space as is to add "Blog" in the top level menu,

adding it in "community" feels hidden though.

**Comment by Simn** [comment]
Having it under community makes sense to me. We should also feature it prominently on the main page though, but one step after another.

**Comment by Simn** [comment]
By the way @ncannasse, are we gonna have blog.haxe.org as well?

**Comment by ibilon** [comment]
Added it into community.

**Comment by Simn** [comment]
Alright, that looks good!

@markknol: Any idea how we could promote it on the main page in a nice way?

**Comment by ncannasse** [comment]
I'm sure @Merelleya want one single URL for the blog, so I can setup http://blog.haxe.org to redirect on http://haxe.org/blog if that's what you want

**Comment by Merelleya** [comment]
Yes, just one, please

**Comment by markknol** [comment]
I think it can have a nice place in the new nav.

**Comment by markknol** [comment]
I made it a main item in the new nav.

**Comment by Simn** [comment]
This has been resolved.
