### ISSUE TITLE
Syntax highlighting issue in Blog

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe.org#172]
Syntax highlighting is not applied when you open a blog post from the list, e.g.

go here http://haxe.org/blog/ and click at my `import.hx` post - code samples won't be highlighted
but if you open http://haxe.org/blog/importhx-intro directly, they will be

**Comment by Simn** [comment]
wtf...

**Comment by nadako** [comment]
I think that's related to the fact content are loaded by js code without refreshing browser page, it's missing some highlighting init call or something.

**Comment by ibilon** [comment]
The number of comments is also missing,
and if you go directly to it then "community" isn't colored.

I'll look into these.

**Comment by ibilon** [comment]
Alright I fixed the syntax highlighting locally, but it requires modification to https://github.com/ufront/ufblog/
I made a pull request https://github.com/ufront/ufblog/pull/1

**Comment by ibilon** [comment]
Actually my solution was bad, we need a dev version of ufront-mvc which has code to reload script annotated `uf-reload`, which includes the one we use to highlight the code.

**Comment by ibilon** [comment]
Fixed on staging.
