### ISSUE TITLE
Implement OpenSearch for Chrome auto search suggestion

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe.org#175]
Per my [Twitter conversation](https://twitter.com/Jeff__Ward/status/710915653541048320) that got a bit long winded, we discovered that the haxe.pl website sticks in the chrome search bar because they've implemented "OpenSearch" (see this [blog post](http://blog.coredumped.org/2012/04/opensearch-how-to-get-google-chrome-to.html) for quick details.)

Please consider adding this to haxe.org. It adds the following search suggestion in the chrome browser bar when typing haxe-related things:

![image](https://cloud.githubusercontent.com/assets/2192439/13892968/7688a62e-ed20-11e5-8063-e9e6c538ded4.png)

So irritating with haxe.pl, but it'd be so convenient with haxe.org !

Downside: it could be seen as intrusive, but many websites do use it. Check out your Chrome settings -> search -> manage search engines to view the list of site who've registered for search in your browser. (And from here you can delete those registrations.)

**Comment by markknol** [comment]
This would be relative easy to do:

the search on haxe.org works like this:
`http://staging.haxe.org/search?s=keyword`

We need to add this meta-tag:

```html
<link rel="search" type="application/opensearchdescription+xml" href="http://haxe.org/opensearch.xml" title="Haxe Search" />
```

The `opensearch.xml` file should look like this: 
```xml
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
   <ShortName>Haxe</ShortName>
   <Description>Haxe - The Cross-platform Toolkit</Description>
   <Url type="text/html" method="get" template="http://haxe.org/search?s={searchTerms}"/>
   <Image height="16" width="16" type="image/vnd.microsoft.icon">http://haxe.org/favicon.ico</Image>
   <moz:SearchForm>http://haxe.org/search</moz:SearchForm>
   <Url type="application/opensearchdescription+xml" rel="self" template="http://haxe.org/opensearch.xml"/>
</OpenSearchDescription>
```

**Comment by markknol** [comment]
Done https://github.com/HaxeFoundation/haxe.org/commit/5f2943a6b5e490bdc25765ee372ab0319c4bc6c3
