### ISSUE TITLE
Server upgrades

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe.org#177]
It is about the server, which hosts haxe.org, lib.haxe.org, nekovm.org, and other sites. This issue is opened here just because we don't have a dedicated repo for the server.

There are things about the server that need to be improved:
- use of Debian Squeeze which reached its EOL on 2016-02-29
  - unable to install new software from apt-get
  - missing security fixes
- no SSL configured
  - haxelib is insecure, people may inject malicious code by modifying traffic content

Since an OS upgrade is needed anyway, maybe we should move things to the cloud.
I'm pretty interested in trying out Amazon EC2 or DigitalOcean. Particularly for their Docker container services which could reduce effort on testing/upgrading.
@ncannasse Could I move a site there to experiment? Or do you have other suggestions?

**Comment by ibilon** [comment]
Haxelib could really use some ssl, it barely need more cpu, and there's free ssl certificate now https://letsencrypt.org/

(While at it we also need to upgrade the usage of md5 for haxelib password, it's been broken for so many years, but that's not a server issue.)

**Comment by nadako** [comment]
Now when Haxe has [bundled SSL support](https://github.com/HaxeFoundation/haxe/pull/5014), it would be really great to connect to haxelib repo/server through https.

**Comment by andyli** [comment]
Progress: I've just moved haxe.org to AWS Elastic Beanstalk and have enabled https (try it: https://haxe.org/). If everything works fine (no problem reported) and I will move the remaining lib.haxe.org, api.haxe.org, and nekovm.org there as well.

**Comment by ibilon** [comment]
Works great, awesome work @andyli!

**Comment by ibilon** [comment]
Actually spoke too soon, got connection issue on firefox,
it loads ok (even without cache) on chrome, but fails with "Unable to connect" on firefox,
same for curl/wget "Failed to connect to haxe.org port 443: Connection refused".

No issue for https://staging.haxe.org

**Comment by nadako** [comment]
neither https://haxe.org, neither https://staging.haxe.org work for me :(

**Comment by ibilon** [comment]
It works on my laptop, so I checked with ping and I don't get the same ip, must be a dns issue.

**Comment by andyli** [comment]
I'm not sure but I also guess it is a temp dns issue.
The TTL is set to 3 hours in the previous DNS (gandi.net's). Now we're using Amazon's DNS servers with TTL set to 5 minutes (easy for me to make changes).
So I guess in the first 3 hours it may still be possible to resolve to the old server. Do you guy still have problem now?

**Comment by nadako** [comment]
works for me now

**Comment by ibilon** [comment]
All good for me too.
Should be fine to redirect http to https.

**Comment by ibilon** [comment]
One of the last http resource called when using https is the gravatar on the blog,
will be fixed by https://github.com/ufront/ufblog/pull/2

**Comment by clemos** [comment]
Hi ! What should I do to setup https://try.haxe.org ?
https://github.com/HaxeFoundation/haxe.org/issues/183

**Comment by ibilon** [comment]
To be all https we still need to add it to:
* api.haxe.org
* try.haxe.org
* haxedevelop.org (we're the ones maintaining it?)
* old.haxe.org
* code.haxe.org
* http://hxbuilds.s3-website-us-east-1.amazonaws.com/builds/haxe/index.html
* learn.haxe.org
* hashlink.haxe.org
* nekovm.org

quite a lot :)

**Comment by clemos** [comment]
As HTTPS is also required for [try.haxe embeds](https://github.com/clemos/try-haxe/issues/105#issuecomment-277701450), I would be happy to setup HTTPS on my try.haxe server.
Can someone from the foundation help me ?

**Comment by frabbit** [comment]
hey @clemos, this is a good tutorial for letsencrypt https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-14-04

**Comment by clemos** [comment]
I (more or less) know how to do that, but I thought maybe using a global `haxe.org` certificate would be possible / easier ?

**Comment by andyli** [comment]
Our haxe.org cert is issued by AWS. I'm not sure if it is possible to use it in non-AWS servers.
I guess using letsencrypt for try.haxe.org would be simplier.

**Comment by clemos** [comment]
FYI it is done for try.haxe.org ;)

**Comment by markknol** [comment]
I think this is done now too, most sites are https 🎉 Lets open new tickets if there is something else to do.
