### ISSUE TITLE
blog.haxe.org redirect / subdomain convention?

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe.org#178]
Currently [lib.haxe.org](http://lib.haxe.org) and [try.haxe.org](http://try.haxe.org) go to their respective pages, while [blog.haxe.org](http://blog.haxe.org) shows a default Apache page:

![image](https://cloud.githubusercontent.com/assets/2192439/14061061/21a616ba-f33c-11e5-9229-b781eec616b7.png)

It'd be nice if blog.haxe.org did any of the following:

1) redirect to http://haxe.org/blog
2) actually be the address for the blog (follow subdomain convention)
3) Not my preference, but it could 404 instead of showing the default apache page

BTW, looks like it was mentioned over here (#170) 3 weeks ago.

**Comment by ibilon** [comment]
I vote for redirection to `/blog`.

It'd be nice to also do that for haxelib, that way we could have `staging.haxe.org/lib` (https://github.com/HaxeFoundation/haxelib/pull/327)

Although that might complicate deployment, what do you think @andyli?

**Comment by andyli** [comment]
Using a different subdomain for each subsite would be easier to relocate
them to dedicated servers, in case we want to do so in the future. But
thats not a huge problem since we can redirect old urls to the new ones
anyway.

**Comment by markknol** [comment]
We now have blog.haxe.org, which redirects to the blog.
