### ISSUE TITLE
Broken links in home page footer section

### ISSUE THREAD

**Issue by Jeeppler** [HaxeFoundation/haxe.org#191]
Hello, 

I found broken links in home page footer in the "learn haxe" section:

- API Documentation ->  http://haxe.org/http://api.haxe.org/
- Try Haxe -> http://haxe.org/http://try.haxe.org/
- Haxelib -> http://haxe.org/http://lib.haxe.org/
- Code Cookbook -> http://haxe.org/http://code.haxe.org/

the error pattern for all for links is the same: they have a http://haxe.org/ in front of the subdomain link.

**Comment by markknol** [comment]
This is already fixed on staging.

**Comment by Jeeppler** [comment]
:+1:

**Comment by markknol** [comment]
its live
