### ISSUE TITLE
Lua (logo) target on homepage

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe.org#194]
I needed it for a presentation, so here it is.

![all-targets-lua](https://cloud.githubusercontent.com/assets/907219/14941485/39537be4-0f9e-11e6-8404-718c2b8ed432.png)

![lua-orange](https://cloud.githubusercontent.com/assets/907219/14941486/416251a2-0f9e-11e6-8f46-1a47ed4c6479.png)

[all-haxe-targets-plus-lua.zip](https://github.com/HaxeFoundation/haxe.org/files/244076/all-haxe-targets-plus-lua.zip)

**Comment by markknol** [comment]
thanks, but when i open the SVG most logos seem broken?

![image](https://cloud.githubusercontent.com/assets/576184/15113034/2f23405a-15f2-11e6-832b-d9cfbb693640.png)

**Comment by MatthijsKamstra** [comment]
the same here... 
let's try that again

[all-targets.svg.zip](https://github.com/HaxeFoundation/haxe.org/files/255005/all-targets.svg.zip)

**Comment by markknol** [comment]
Thanks!
