### ISSUE TITLE
[3.3-rc1] duplicate type parameters error also when used with 'Const'

### ISSUE THREAD

**Issue by sledorze** [HaxeFoundation/haxe.org#198]
This generates an error:

class Foo<Const,Const> {}

Const can be very useful with macros and I don't understand why it should be restricted.

**Comment by markknol** [comment]
I think this is an Haxe issue, not a haxe.org issue. 
Would you mind to post it here? https://github.com/HaxeFoundation/haxe/issues

cc @Simn

**Comment by sledorze** [comment]
@markknol oups thanks, my bad.. :)
