### ISSUE TITLE
Content for the "Games" use case

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#2]
If you have any content for the "games" use case page, please leave a comment here.

We are looking for:

* __Testimonials / Quotes__:  If you have used haxe for creating games and it has been awesome, leave a short 1 sentance quote, with your name, company and URL.
* __Showcase__: If you have a game you would like included in the showcase, please include the name of your game, an image for the carousel, and a 1 line description.
* __Popular Libraries__: If there's a library that is used by a large number of Haxe game developers and we've left it out, let us know.
* __Tutorials__: if you have a tutorial, please supply a link, a title, and a 1 line description.

Please note we are not going to guarantee that items posted here will be included.  

Once we have enough content we can close this issue.

**Comment by Simn** [comment]
Closing this as I think we're good on the Games content.
