### ISSUE TITLE
Partners list

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#207]
Here's a new partner to be added as part of the supported lists:

Veith System http://www.veith-system.de/
Logo : 
![veith-system](https://cloud.githubusercontent.com/assets/1022912/16176276/bebf2386-360a-11e6-9ec4-8ec13adcf11c.png)

**Comment by ncannasse** [comment]
Please also remove Stencyl.

**Comment by markknol** [comment]
I've put it on staging https://github.com/HaxeFoundation/haxe.org/pull/208

**Comment by ibilon** [comment]
On master now.

**Comment by ncannasse** [comment]
Thanks!
