### ISSUE TITLE
Blog list, no background image = invalid asset request

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe.org#209]
At https://haxe.org/blog/

Ends up asking for `https://haxe.org/blog/this-is-not-the-variable-you-are-looking-for/files/null?w=1600` which return error 500.

Also happens for "New language feature: import.hx".

Should be easy to fix, will look at it.

**Comment by ibilon** [comment]
Still one left with error 500, in https://haxe.org/blog/haxe-api-documentation-tool it tries to load https://haxe.org/blog/haxe-api-documentation-tool/files/dox-update.png?w=1600 but `failed to download s3://haxe-blog/blog-uploads/19/dox-update.png to /var/www/html/uf-content/blog-uploads/19/dox-update.png`
@markknol could you check if your post really has the image? and if it does could you try reuploading it?

**Comment by markknol** [comment]
It had one but got lost somewhere after publishing it. Will reupload soon.
