### ISSUE TITLE
Nightly builds links.

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe.org#21]
It may be useful to provide links to nightly builds on the downloads page or some dedicated page.

**Comment by Simn** [comment]
Sorry for ranting but issues like this being open for 9 months make me quite sad. We really need someone who feels responsible for this repository and the website in general.

If @jasononeil only wants to deal with the technical side of things that's fine with me, I just need to know. I can "take over" the main maintenance of this repository now that I have @Merelleya to assist me content-wise.

Only thing I still need to know is how to actually publish changes.

**Comment by ncannasse** [comment]
@jasononeil could you connect with @Simn so he can publish updates on haxe.org ?
(@Simn ; @jasononeil is currently focusing on updating lib.haxe.org)

**Comment by Simn** [comment]
Ehm, that's good to know. I was looking at lib.haxe.org today and felt the need to do something. After consulting @markknol he sent me a quick suggestion for a change: http://i.snag.gy/GKckS.jpg

I had actually planned to just replace the template and css files once it looks good but if that's already taken care of I'll sit back and wait.

**Comment by ncannasse** [comment]
Looks nice ! let's have @jasononeil and @markknol work together on this !

**Comment by jasononeil** [comment]
Re: haxelib - That's pretty similar to what I'm doing.  I'll try upload a test site later today.  Would be great to get your feedback @markknol 

Re: updates - Any commit to "master" on HaxeFoundation/haxe.org will now be automatically deployed to the website (via Travis).  Anything that is more than a simple content change should be run locally to test it out first.  Looks like @Simn was able to fix the issues he had in #97?

Re: the actual issue:

1. Is it just a link to http://builds.haxe.org , or are you hoping for something prettier?
2. In terms of where to place the link;  I think a link on the "All Versions" page, and also one on the main "/download/" page.  Currently this is just the page for the latest version, so I'm having trouble deciding where it would be sensible to put the link.  Perhaps in the top right corner, where there is usually a link to the prev/next version, we could provide a link to the nightlies as the "next version" (see attached).

![build link](https://cloud.githubusercontent.com/assets/315158/6360963/3330156c-bcb9-11e4-8c45-dec88e98475f.png)

**Comment by Simn** [comment]
Semantically it makes a lot of sense to put it there because the flow is old <- > new, and nightly builds are the newest.

There should also be a link at http://haxe.org/download/list/. It should be fine to put that at the top there (not in the list itself).

**Comment by ncannasse** [comment]
works for me too

**Comment by jasononeil** [comment]
In response to the rant:  it's a fair judgement.  Something that's only 10 minutes work shouldn't take that 9 months to fix.  It would be wise for someone else to be the content king for the website - @Simn if you and @Merelleya are eager I think you would be the most qualified for both the technical content and the marketing content.

Now that Travis is working for deployments it should make things easier.  Anything you want me to look at let me know, I'll try work through the things you've already assigned to me.

**Comment by markknol** [comment]
@jasononeil  Ah so we both redesign haxelib? Atm, mine now looks+works like this
![haxelib](https://cloud.githubusercontent.com/assets/576184/6362345/642d4dc4-bc8c-11e4-99a7-4a9932be6128.gif)

Some things
 * The profile page; I use gravatar images using the emailadress field to give bit of personality
 * The project pages try to check if link is github, and then [displays star/fork buttons](https://ghbtns.com/) with counters
 * The landingspage is not really attractive yet

**Comment by jasononeil** [comment]
Nice, I like the use of gravatar and github stats.

Have you got any of this content online yet?

**Comment by jasononeil** [comment]
(Or at least the HTML templates).  I might try steal the profile page
especially I might steal :)

**Comment by markknol** [comment]
I don't have them online, but I can create a branch tonight so you can check it out. I'd like to help you.

**Comment by Simn** [comment]
This looks really good, please get this live ASAP. :)

**Comment by ncannasse** [comment]
Regarding the new haxelib website : could we have a home similar to http://opam.ocaml.org/ that explains how to install libraries and how to package one as well ? (+ most downloads libs, etc.)

**Comment by markknol** [comment]
Hi Nicolas, I've send my templates to Jason :smile:  :boom:

I've put a small line on every projectpage that also explains how to install in one sentence.

![small-note](https://cloud.githubusercontent.com/assets/576184/6380829/c9265954-bd3c-11e4-8394-6e0a00e0f406.PNG)

In my template files it links to  [this page](http://haxe.org/manual/haxelib-using.html)  I recently wrote for the manual, maybe we can duplicate content for this website and link to that.

**Comment by Simn** [comment]
Looks good, I like that blue arrow in particular. :)

**Comment by markknol** [comment]
It should animate too.

**Comment by nadako** [comment]
How about we render a `README.md` or something there? Like npm does.

**Comment by markknol** [comment]
That is a good suggestion to add, when the project links to a github page (not always the case, since you can fill in whatever for the website field)
