### ISSUE TITLE
Update Haxe Windows building 

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#212]
Get rid of the MSVC instructions and go with OCaml 4 instead.

@nadako @ncannasse

**Comment by nadako** [comment]
We should decide what version we use. Nicolas was using this OCPWin thing, while I had no success installing it. This one works for me tho: http://protz.github.io/ocaml-installer/ (and there's a build instruction for it on the website)

**Comment by nadako** [comment]
I somehow managed to build [merlin](https://the-lambda-church.github.io/merlin/) on that ocaml and this now works for me: https://github.com/hackwaly/vscode-ocaml. We should find out the exact steps for that tho.

**Comment by ncannasse** [comment]
@nadako what kind of error did you get by using OCPWin?
Would anyone with a "clean" windows machine could try?

**Comment by ibilon** [comment]
Was that fixed by https://github.com/HaxeFoundation/haxe.org/commit/dd732e37fa797fabfb9cbdc1886b49fe916fed47?

**Comment by Simn** [comment]
Yep!
