### ISSUE TITLE
Broken img

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#213]
On this page one image is not loading:
http://haxe.org/use-cases/who-uses-haxe.html

**Comment by ibilon** [comment]
The file is `https://haxe.org/img/partners/knowledge-players-logo.png`,
and was removed by https://github.com/HaxeFoundation/haxe.org/commit/24b67659974f7c7b41028d413d4da24d0136bf04

Should it be added back? or removed from "Companies using Haxe"?

**Comment by ncannasse** [comment]
it should be added back, also e-buzzing logo should be resized down maybe :)

**Comment by ibilon** [comment]
done.
