### ISSUE TITLE
lib.haxe.org cross tag errors

### ISSUE THREAD

**Issue by skwerlman** [HaxeFoundation/haxe.org#214]
Attempting to view the cross tag on lib.haxe.org (http://lib.haxe.org/t/cross/) results in an uncaught error.

**Comment by ibilon** [comment]
That's a haxelib issue, could you reopen at https://github.com/HaxeFoundation/haxelib?
Thanks.

**Comment by skwerlman** [comment]
Done: HaxeFoundation/haxelib#342
