### ISSUE TITLE
Ideally lib.haxe.org social metadata should describe the library, not haxe itself

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe.org#218]
It's a small issue, and perhaps debatable, but:

**The issue:** When posting links on social media to haxe libraries (e.g. http://lib.haxe.org/p/hx-color-trace) -- the post shows a description of Haxe itself:

![image](https://cloud.githubusercontent.com/assets/2192439/18362732/3530f140-75c4-11e6-9d38-73b3afc3b72f.png)

There's a set of metadata tags that set the description for each page. I suspect these are defaults inherited from haxe.org webpages:

![image](https://cloud.githubusercontent.com/assets/2192439/18362760/547171f6-75c4-11e6-8b46-291557cc63bf.png)

**The suggested solution:** It's my opinion that these metatags should, for the haxelib pages, describe the library, not Haxe itself. e.g.

![image](https://cloud.githubusercontent.com/assets/2192439/18362861/c8d73d50-75c4-11e6-9716-e7ed66b93aa5.png)

**Optional related TODO:** check other haxe.org pages

But even I'll admit, it's a low-priority nit. :)

**Comment by nadako** [comment]
summon @markknol \o/

**Comment by markknol** [comment]
Good point, will look into this.

**Comment by markknol** [comment]
Btw I close it here, since there seems already a related ticket for it on haxelib. https://github.com/HaxeFoundation/haxelib/issues/328

**Comment by jcward** [comment]
Ah, I didn't know whether to file on haxe.org or haxelib, and checked here for dupes, but not there. Thanks, Mark and Dan.

**Comment by markknol** [comment]
No problem, thanks for reminding me :)
