### ISSUE TITLE
404 page - top navigation is incorrect

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#219]
http://staging.haxe.org/so-wrong/so-wrong

It also displays some pages that shouldnt be there.

**Comment by ibilon** [comment]
https://github.com/HaxeFoundation/haxe.org/blob/staging/src/app/view/error.html

it's not templated so it ends up out of sync

**Comment by markknol** [comment]
I copy pasted the generated nav to it.
