### ISSUE TITLE
New partner!

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#220]
Could someone update the partners list by adding Gamesys using one of the following logos (resized) as part of the HF supporters?

Thanks

![gamesys-logo-01](https://cloud.githubusercontent.com/assets/1022912/18520629/f0280036-7aa8-11e6-93b4-dabbe2b44328.png)
![gamesys-logo-01-1](https://cloud.githubusercontent.com/assets/1022912/18520628/f016fb60-7aa8-11e6-8f35-2e664c3f67e3.png)
![gamesys-logo-02](https://cloud.githubusercontent.com/assets/1022912/18520630/f03e02c8-7aa8-11e6-845d-46d3b514f136.png)

**Comment by ncannasse** [comment]
PS : URL is http://www.gamesyscorporate.com/

**Comment by RenKloppers** [comment]
Great, thanks for this Nicolas, looking forward to the preview.

**Comment by ibilon** [comment]
It's on staging
http://staging.haxe.org/
http://staging.haxe.org/foundation/

should I push to master?

**Comment by RenKloppers** [comment]
Looks great! Thank you, happy for you to push the change.

**Comment by ncannasse** [comment]
Thanks @ibilon and yes please push

**Comment by ibilon** [comment]
It's now live.

**Comment by RenKloppers** [comment]
Many thanks!
