### ISSUE TITLE
redirect http to https

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#221]
Now we have SSL on our website, it would be nice if we can setup the server to redirect from http to https.
How something like this work in ufront?

**Comment by ibilon** [comment]
Do you want to deal with this at ufront level?
I'd use the apache rewrite module.

**Comment by markknol** [comment]
Ah yes thats fine too.

**Comment by ibilon** [comment]
Now that we have neither ufront nor apache we'll need something else,
@andyli does S3 have anything to do that?

**Comment by andyli** [comment]
I configured CloudFront to do http -> https redirect for staging.haxe.org. It should work within an hour. After we checked that's ok, I can set up the same thing for haxe.org.

**Comment by markknol** [comment]
Since try.haxe now is https too, I think we can turn this on on haxe.org too.

**Comment by markknol** [comment]
@andyli can we redirect by default?

Also what would it take to have all domains on https?

**Comment by andyli** [comment]
lib.haxe.org: https://github.com/HaxeFoundation/haxelib/issues/10
nekovm.org: https://github.com/HaxeFoundation/nekovm.org/issues/15
summit.haxe.org: https://github.com/HaxeSummit2017/organization/issues/25

Other than those, I think I've set up https (with auto redirect) for all other websites. If I miss any, open an issue for me.
