### ISSUE TITLE
Heaps Engine missing from game tools list

### ISSUE THREAD

**Issue by jgamedev** [HaxeFoundation/haxe.org#222]
N. Canasse's Heaps reference is missing in this page:
https://haxe.org/use-cases/games/

**Comment by ncannasse** [comment]
I think we should remove HaxePunk which is no longer maintained, and maybe also add KHA

**Comment by ibilon** [comment]
Haxepunk got some activity recently, flambe though doesn't seem maintained any more.

I agree about ading Kha, but I don't think heaps is popular enough yet.

**Comment by markknol** [comment]
Well flambe still works, we use it for lots of projects. I think the goal of this list is to provide options so lets not remove stuff. Adding heaps/kha is a good idea.

**Comment by ibilon** [comment]
Done in #224
