### ISSUE TITLE
Blog Header Image

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#223]
Uploading an header image for the blog seems to be broken, I'm getting the following error in console:
`app.min.js:1 ufblog.posts.SetupEditFormAction.setupHeaderUploadHandler()[146]: Failed: Error: Error with response for ufblog.posts.AttachmentApi.uploadHeaderImage(22,[object Object]): no remoting response found AttachmentApiAsync.uploadHeaderImage:0`

**Comment by ibilon** [comment]
With the new code the background image is added to the repo, so that won't be a problem anymore.
