### ISSUE TITLE
Partners Changes

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#230]
Happy new year !

Two changes are to be made to the partners list:

- removal of ChameleonJohn 
- addition of InnoGames (here's the logo source 
![innogames](https://cloud.githubusercontent.com/assets/1022912/21594185/db20fd1e-d11f-11e6-86c3-e0133427856b.png) https://www.innogames.com/

**Comment by ibilon** [comment]
I noticed that the home page has veith system as partner but not the foundation page, which has stencyl.

@ncannasse which partners are supposed to be there?

**Comment by ncannasse** [comment]
Veith System should, Stencyl should not :)
