### ISSUE TITLE
haxe.org sub domains

### ISSUE THREAD

**Issue by zabojad** [HaxeFoundation/haxe.org#233]
Hi there !

I've just noticed that any subdomain on haxe.org returns a "It works" page. It doesn't look very clean, maybe you should return a nice HTTP 404 as Github does for example :

http://hapi.haxe.org/
http://toto.haxe.org/

http://toto.github.io/

**Comment by markknol** [comment]
@andyli Can we redirect invalid domains to haxe.org?

**Comment by andyli** [comment]
I've just deleted the `*.haxe.org` DNS record, so they wouldn't work anymore.
Hopefully there is no secrete website that relies on it...

**Comment by markknol** [comment]
Thanks!

**Comment by markknol** [comment]
@andyli  http://blog.haxe.org/ did redirect to http://haxe.org/blog, can we get this back?

**Comment by andyli** [comment]
Done :)
