### ISSUE TITLE
Nested lists are not rendered correctly anymore

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#234]
Compare https://haxe.org/documentation/introduction/building-haxe.html and https://github.com/HaxeFoundation/haxe.org/blob/staging/pages/documentation/introduction/building-haxe.md

**Comment by markknol** [comment]
@nadako fixed this case here https://github.com/HaxeFoundation/haxe.org/commit/147ba15b23c7b2de0184e58e7f55bc7fe220fa51

Other than that, this is a haxe-markdown issue, see https://github.com/dpeek/haxe-markdown/issues/17 and https://github.com/dpeek/haxe-markdown/issues/19
