### ISSUE TITLE
"A taste of Haxe" frame unavailable due to missing HTTPS

### ISSUE THREAD

**Issue by anissen** [HaxeFoundation/haxe.org#236]
The "_A taste of Haxe_" frame on the frontpage of [haxe.org](http://haxe.org/) is unavailable. Observed using the latest Chrome and Safari on Mac.

Here's the error description:

> Mixed Content: The page at 'https://haxe.org/' was loaded over HTTPS, but requested an insecure resource 'http://try.haxe.org/embed/A75dd'. This request has been blocked; the content must be served over HTTPS.

Heads-up @markknol @ibilon @andyli

**Comment by Simn** [comment]
Fixed by https://github.com/HaxeFoundation/haxe.org/commit/7fecd2500eae9c05fad45b89e8e0ef75dd140e7b

**Comment by ibilon** [comment]
I merged #235 until we add https to try haxe.

**Comment by anissen** [comment]
Oh, my bad! That was using https://haxe.org/ (HTTPS) and not simply http://haxe.org/ (HTTP)

**Comment by Simn** [comment]
Yes, we knew about this and there was a PR to fix it, somebody just had to press the button.
