### ISSUE TITLE
http://haxe.org/api page is not displayed/have no content.

### ISSUE THREAD

**Issue by dnistreanu** [HaxeFoundation/haxe.org#238]
http://haxe.org/api page is not displayed/have no content. **Where I can get all API info ?** Thanks.

**Comment by ibilon** [comment]
http://api.haxe.org/

I don't think http://haxe.org/api ever existed, where did you got this link?

**Comment by dnistreanu** [comment]
http://haxe.us/haxe_tutorial.html , I got this link for an interview appointment and I need haxe API to learn it.

**Comment by ibilon** [comment]
That tutorial is too old, its examples wont work with a recent haxe.

The links are from the old old haxe.org version, not much that can be done.

**Comment by markknol** [comment]
I've added a redirect for that on staging
