### ISSUE TITLE
Haxe tutorial for beginners with actual mini apps examples ?

### ISSUE THREAD

**Issue by dnistreanu** [HaxeFoundation/haxe.org#239]
Beside http://haxe.org/manual is any recommended source to learn haxe development while creating actual mini apps ?  If not I think it would be a good idea. Thanks.

**Comment by Simn** [comment]
This is not an actionable issue. If you have a question, refer to one of the communication channels listed here: https://haxe.org/foundation/contact.html

**Comment by markknol** [comment]
@dnistreanu Not sure if you are aware, but there is http://code.haxe.org, where we collect code snippets and more real life examples of how to use Haxe in practice.
