### ISSUE TITLE
Home page redesign

### ISSUE THREAD

**Issue by dagnelies** [HaxeFoundation/haxe.org#245]
Hi,

I used to use HaXe long ago, back in the historical days when it was still the old site and when HaXe was transitioning to version 2.

Now I came back, saw the new site and though...

- first: wow, it looks good, fresh and modern
- after little moment: dammit, the content went from useful into diluted distracting bla bla

---

To illustrate my point, on the old site, just by looking at it, you see:

- multiplatform
- haxe foundation
- familiar syntax
- strictly typed
- modern features
- open source

...and a bit more info about these features. It's light and informative. At first glance you get an idea what to expect. Sounds promising.

---

Let's do the same check "I read the headlines first" on the new site:

- what is haxe
- what haxe is not
- who uses haxe
- open source / haxe foundation

...and a lot of the texts sound just like hot air. Let's take the first one:

> Haxe is an open source toolkit based on a modern high level strictly typed programming language, a state-of-the-art light-speed cross-compiler, a complete cross-platform standard library, and ways to access to each platform's native capabilities.

1. It's a very very very long sentence
2. The first big chunk of it is just repeating the headline
3.  filled with superlatives (modern, high level, state-of-the-art, light-speed, complete) which just sounds like boasting without being informative
4. if you remove the noise, it sounds like "Haxe is a toolkit based on a strictly typed programming language with a cross-platform standard library and access to native capabilities."

----

Now to the second:

> Haxe is not a high level framework. It's a toolkit that can be used to build [...] frameworks. 

...come on, are you serious? What kind of explanation is that?!?! By the way, I still find the choice to call HaXe a "toolkit" rather than a PL fairly disturbing.

---

In the old site, for instance, the first paragraph was:

> Haxe can be compiled to all popular programming platforms with its fast compiler – JavaScript, Flash, NekoVM, PHP, C++, C# and Java – which means your apps will support all popular mobile devices, such as iOS, Android, BlackBerry and more.

Now, that is clear, concise, you know what to expect. The new site, with all due respect, is just the opposite. It leaves a rather foggy impression, with a lot of noise and self-boasting.

Just my 2 cents. If you ask me, I prefer content/presentation of the old site by far.

PS: ...the designer did a good job though, great aesthetics. 👍

**Comment by markknol** [comment]
Thanks for your feedback! Making the homepage cleaner is on our list for sure :)

**Comment by dagnelies** [comment]
I apologize for the rudeness of my post while I am at it, it was a bit of a rant. Overall, it's nice to see that things are moving forward ...and Haxe from now on, got it.

**Comment by markknol** [comment]
Ill close this since we kinda have a plan for the new homepage. Ill definitely take your words in account.
https://github.com/HaxeFoundation/haxe.org/issues/273
