### ISSUE TITLE
versions.json Error 404 on website

### ISSUE THREAD

**Issue by aliokan** [HaxeFoundation/haxe.org#247]
The file still in [sources code](https://github.com/HaxeFoundation/haxe.org/blob/staging/downloads/versions.json), but not found on the website : http://haxe.org/website-content/downloads/versions.json  

I have tried to find why is not available any more, without success.

**Comment by andyli** [comment]
Probably it is because the file is not copied to the destination folder during site generation.

@ibilon Can we copy that also? I think the version info is quite useful for 3rd-party automation. I can probably use that for TravisCI Haxe support too.

**Comment by ibilon** [comment]
It's a configuration file, doesn't need to be available online.

You can download it through github https://raw.githubusercontent.com/HaxeFoundation/haxe.org/staging/downloads/versions.json

**Comment by ibilon** [comment]
@andily ok, I'll add it
