### ISSUE TITLE
Replace the custom syntax highlighter

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/haxe.org#248]
For the haxe code:

* look into pre processing it
* or use the emscripten version of what vscode does (it's slow but there's not much code)

For others (snippets of js/lua ...) find a js library for it.

**Comment by markknol** [comment]
Do we have lua snippets?

**Comment by ibilon** [comment]
Just one in https://haxe.org/blog/hello-lua/

**Comment by markknol** [comment]
Ill close this for now, since I don't think it is worth the effort.
