### ISSUE TITLE
Replace/update Google Site Search

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe.org#249]
this: https://enterprise.google.com/search/products/gss.html

> On April 1, 2017, Google will discontinue sales of the Google Site Search. All new purchases and renewals must take place before this date. The product will be completely shut down by April 1, 2018.

it seems that the new price will be $100 per year for 20.000 search queries /yr

**Comment by MatthijsKamstra** [comment]
damn... I reported this twice (sorry @markknol )

**Comment by markknol** [comment]
If you feel adventurous, please PR :)

**Comment by MatthijsKamstra** [comment]
it doesn't look that complicated (https://developers.google.com/custom-search/docs/element).
But what I posted here, it looks like you need to pay for it?

So that might be a little problem, not that difficult, but probably you need to use HaxeFoundation money for that.

And in the past I tried to build the Haxe website and failed miserably.

**Comment by markknol** [comment]
I added new search api, wasnt that hard at all. Thanks Google!
