### ISSUE TITLE
Compiler Targets should mention Node, javascript is not explicit enough?

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/haxe.org#250]
https://github.com/HaxeFoundation/haxe.org/blob/staging/pages/documentation/introduction/compiler-targets.md

Compiler Targets should mention Node, javascript is not explicit enough?  Nodejs was added to Haxe ecosystem with the release of hxNodejs haxelib so much later than javascript itself, this is somewhat similar to PHP and PHP7 and flash and AS3.  It's important to mention Node because of it's current comercial draw, while javascript may cover it, it's useful to use the word Node and it would seem fair to indicate it's full supported use is rather recent.

**Comment by Simn** [comment]
The target language is JavaScript. Whether you run it through node, pass it to your browser or print it out makes no difference.

**Comment by Gama11** [comment]
Also, there's a NodeJS logo here:

![](http://i.imgur.com/mhvlDmw.png)

**Comment by markknol** [comment]
That is just marketing, just like the ios/android logo.

**Comment by nadako** [comment]
Actually, genjs has some explicit nodejs support (escaping its globals, like `process` and whatnot)

**Comment by ibilon** [comment]
Last time we discussed this we concluded that considering the limited support of nodejs through hxnodejs it wasn't the best to say we support nodejs as a target.

**Comment by Justinfront** [comment]
For Marketing it makes a difference the appearance of the word "Node" on the page is worthwhile.

**Comment by markknol** [comment]
We support node, but its not a target.

**Comment by ncannasse** [comment]
I agree that from a marketing perspective adding a Node logo would be worthwhile
