### ISSUE TITLE
Haxe 3.4.0 64 bit linux binaries download is wrong file

### ISSUE THREAD

**Issue by asciiascetic** [HaxeFoundation/haxe.org#255]
Having installed 3.4.0 only a week ago, I wanted to install it again on another machine, but was met with this curiosity:

![wrong-archive](https://cloud.githubusercontent.com/assets/1368610/23873192/80f45830-0807-11e7-8903-11aa31729de3.png)

I noticed that the download size is a mere 132 bytes!! Wow, I thought, "the `haxe` compiler must be coded in some kind of interdimensional, informationally massless language. Amazing!" (I should really give OCaml another look.)

Alas, it seems that the compiler isn't magical at all:

``` bash
$ cat haxe-3.4.0-linux64.tar.gz 
version https://git-lfs.github.com/spec/v1
oid sha256:cad51f0e55642a39f5939d16b453b45b8b321b37602ed6d23cc21c2bf514198c
size 5932587

```
 sigh...

**Comment by markknol** [comment]
While Haxe is indeed an amazing cross universe language, this is not intended and we are going to look into it.

**Comment by andyli** [comment]
From [Travis log](https://travis-ci.org/HaxeFoundation/haxe.org#L303-L306):
```
Git LFS: (0 of 133 files) 0 B / 484.28 MB                                      
batch response: This repository is over its data quota. Purchase more data packs to restore access.
batch response: This repository is over its data quota. Purchase more data packs to restore access.
```
Turn out the data quota is pretty low... See https://help.github.com/articles/about-storage-and-bandwidth-usage/
I think this is a recent change?

I guess we have to use GitHub release instead of LFS...

**Comment by Simn** [comment]
Oh man, how did we miss this... I understand GitHub has to make money somehow, but this model won't work for us.

@ibilon: This is a bit of an urgent problem. Any contingency plans?

**Comment by andyli** [comment]
I've just manually replaced the 3.4.0 and 3.2.1 download files in S3. So at least people can get those for now.
I'm still not sure what is the right way of fixing this... since we discussed before, mapping old urls to GitHub release urls is hard (if not impossible). May be we have to throw away the old urls and breaks ppls automation...

**Comment by andyli** [comment]
I kind of have set up the redirection of old urls -> github releases. Can anyone double check if I have missed anything by testing staging.haxe.org?

The way it works now is to call the aws s3 api for each of the files, and set up redirection to github releases. It is done in Travis.

If everything goes well, we need to do the following:
 * merge staging to master
 * modify src/generators/Downloads.hx to fetch the release info using github api
 * remove the binaries in this repo by following https://help.github.com/articles/removing-files-from-a-repository-s-history/

**Comment by andyli** [comment]
Noticed that v1.19 is listed in versions.json but there is not corresponding files in GitHub release. @markknol Would you double check if there is any other versions that are missing and upload them?

**Comment by ibilon** [comment]
That was the code used to fetch info from github https://github.com/HaxeFoundation/haxe.org/blob/ac628b50ee09a3eb85cc04b032970731989ba890/src/GenerateVersionsJson.hx

I think I remember some issues with some naming, I'll check it.

@andyli is the removing from history step required? the git lfs files aren't big

**Comment by andyli** [comment]
> is the removing from history step required? the git lfs files aren't big

Not necessary indeed. There are ~450MB files, that's about 50% of the lfs free storage quota... but it's not like we will use lfs anymore anytime soon...

**Comment by andyli** [comment]
Okay, based on @ibilon's code, I've revised src/generators/Downloads.hx in https://github.com/HaxeFoundation/haxe.org/commit/0408bd1ef7c1681f17e2de8070b84b178b14d84f

**Comment by markknol** [comment]
Looks good to me!

**Comment by andyli** [comment]
Merged to master, seems to work correctly.

**Comment by ncannasse** [comment]
Ah, that was what this GIT LFS email I got was about ! It was not very clear to me what they meant by "LFS" and how we were using it :)
