### ISSUE TITLE
Add social share buttons

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe.org#260]
Many sites offer easy way to share ( at example AddThis http://www.addthis.com/  ) . 
Haxe.org already use opengraph data, so I think some share button on home page will help. 
Also one strange thing which I saw. Haxe site is well optimized for keyword "cross platform toolkit", but according google this keyword have only  up to 100 searches/monthly.
  For other keywords such as:
-  "mobile app development "- up to 100 0000 searches ,  Haxe is not in top 100
- "cross platform app development" - up to 10 000 searches
- "mobile app development tools"  - up to 10 000 searches, Haxe is not in top 100
Also in similar topics on Quora,  haxe is not mention at all.  Same situation in  some blog articles about  popular cross platform languages..
 I think a little more SEO and paid articles  in popular media or blogs will help to popularize haxe

**Comment by markknol** [comment]
Have you ever used such share functionality on a website? I think most users know how to copy paste a link to facebook/twitter. Nevertheless it might be a good addition for the blog.

**Comment by markknol** [comment]
Ill close this issue for now
