### ISSUE TITLE
Support Plans page

### ISSUE THREAD

**Issue by flashultra** [HaxeFoundation/haxe.org#274]
Hi, 
First congrats for HaxeSummit ! Really good conference. Thank you for that !
In one of the  the last sessions the topic was about Haxe finance. I check what support plans offers Haxe community ( from http://haxe.org/foundation/support-plans.html ) and one thing came up. Why you no give option for more expensive support plans ( such as Diamond , Gold or something else ) where the price for year will be 100 000 euro ( -x4-x5 more from the max at the moment). I know that is a much, but I think there have companies which makes enough and maybe they will willing to support Haxe . Of course, may I be  wrong, but at least there will be a choice

**Comment by ncannasse** [comment]
Thank you for the suggestion, but based on the discussion we had with partners so far, the current support plans are appropriate and it would be hard to get more without providing additional services that we don't have for now. 

We might still consider adding one more just for marketing reasons so companies don't feel like they are paying the most expensive package, but we have to figure out first what kind of extra benefits they would get.

**Comment by markknol** [comment]
Ill close this issue for now. Feel free to bring more ideas.
