### ISSUE TITLE
Updated partners

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#276]
Please add Playtika and Docler to the strategic partners list. I haven't got the logo so you can get them from their respective websites, I'll ask if they want some change once it's available online.

**Comment by ibilon** [comment]
Neither website has a logo image usable for us.
@ncannasse could you ask them for one?

**Comment by markknol** [comment]
http://www.itone.lu/sites/itone/files/articles/doclerholding_logo_red.jpg
https://www.playtika.com/sites/all/themes/playtika/images/logo-large.svg

**Comment by ibilon** [comment]
@markknol ah you're better at this than me :D

@ncannasse it's on staging, tell me if that's ok to merge

**Comment by ncannasse** [comment]
Good to merge, thanks !
