### ISSUE TITLE
Partners update

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#278]
Please add FlowPlay (logo here 
<img width="250" alt="b_w_full" src="https://user-images.githubusercontent.com/1022912/31114739-d19a9476-a81f-11e7-8926-f28d8fec4e39.png">) to Strategic Partners

Also, please remove McGraw Hill and Proletariat.

**Comment by ibilon** [comment]
It's on staging, will push live soon.
