### ISSUE TITLE
Distinguish Windows 32/64 bit builds

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#280]
Since we're going to have both 32 and 64 bit builds for Haxe 4, it's necessary to distinguish them on the download page. We can use the current file name scheme for 32 bit builds, and use `haxe-3.4.3-win64.exe`/`haxe-3.4.3-win64.zip` for the 64 bit ones.

**Comment by ibilon** [comment]
Done (on staging).
