### ISSUE TITLE
Automate api.haxe.org

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#281]
Would be nice to make api.haxe.org be automatically deploy theapi docs of the current Haxe version and have a history of older versions online too.

* [x] http://api.haxe.org/v/dev should be latest development version (this is already automatically deployed)
* [x] http://api.haxe.org/v/{tag} should be a released version. These versions could be downloaded from Github releases.
* [x] http://api.haxe.org/ should be a current released version (currently @Simn does a manually uploads this)

Related https://github.com/HaxeFoundation/haxe.org/issues/104

**Comment by andyli** [comment]
I changed http://api.haxe.org/v/dev to http://api.haxe.org/v/development, it's longer but I want to keep the branch name. It's possible to enable api docs upload for other branches too.

For, http://api.haxe.org/v/{tag}, the 3.4_bugfix branch is ready - any tag made on that branch will do the required work. The development branch is not ready yet - will fix soon. Currently only 3.4.4 is available, can import the older ones too if we really want.

> http://api.haxe.org/ should be a current released version
This is automated. Any time the site is regenerated, it will look up the latest version from GitHub API and use that. Have to double check whether it is possible the latest version haven't submitted it's API doc to https://github.com/HaxeFoundation/api.haxe.org

**Comment by Simn** [comment]
Great work!

> This is automated. Any time the site is regenerated, it will look up the latest version from GitHub API and use that.

How exactly does it determine that? Say we release 4.0 and then make a 3.4.9 some time later, which one would win?

**Comment by andyli** [comment]
It looks at https://api.github.com/repos/HaxeFoundation/haxe/releases/latest.
I thought it will be smart enough to use 4.0, but [stackoverflow](https://stackoverflow.com/a/22838010/267998) tells me it just use the timestamps...
So I will have to fix it too. Thanks for the careful consideration!

**Comment by markknol** [comment]
This is done 👍 works great
