### ISSUE TITLE
https://haxe.org/search/ is not working

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe.org#287]
search stopped working?

https://haxe.org/search/

```
Unauthorized access to internal API. Please refer to https://support.google.com/customsearch/answer/4542055
```

**Comment by MatthijsKamstra** [comment]
![screen shot 2017-12-08 at 10 13 55](https://user-images.githubusercontent.com/907219/33758961-c28d85b4-dc00-11e7-8834-9fb71570bc13.png)

**Comment by markknol** [comment]
Related to https://github.com/HaxeFoundation/haxe.org/issues/249

**Comment by markknol** [comment]
Ill close this one

**Comment by MatthijsKamstra** [comment]
yes, the other covers it all
