### ISSUE TITLE
navigation update community

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe.org#288]
google groups are now http://community.haxe.org/

![screen shot 2017-12-08 at 13 26 32](https://user-images.githubusercontent.com/907219/33765940-872a67ce-dc1b-11e7-97dc-186466d39498.png)

**Comment by ibilon** [comment]
Progress:

* [X] haxe.org
* [X] hashlink.haxe.org
* [X] haxedevelop.org
* [X] code.haxe.org
* [ ] lib.haxe.org
* [ ] try.haxe.org
* [ ] api.haxe.org

**Comment by markknol** [comment]
This is done now, the new forum + gittr is in there.

api.haxe, lib.haxe and try.haxe sites are in the "learn" menu. There is no need to put haxedevelop and hashlink in the menu.

**Comment by ibilon** [comment]
I meant which site has the new links, not which one should be in the menu ;)

**Comment by markknol** [comment]
try.haxe https://github.com/clemos/try-haxe/pull/142
api.haxe https://github.com/HaxeFoundation/api.haxe.org/pull/1

**Comment by markknol** [comment]
Only lib.haxe PR needs to be updated, then its done.

**Comment by markknol** [comment]
Lib.haxe is merged too, will be live soon. All sites are done now.
