### ISSUE TITLE
Haxe Summit videos valorisation?

### ISSUE THREAD

**Issue by elsassph** [HaxeFoundation/haxe.org#292]
I was checking some videos from last Haxe Summit and I'm a bit underwhelmed by the number of views, and the fact that the foundation didn't even blog about their availability.

A huge amount of effort goes into these conferences, for a relatively small number of people, and absolutely nothing seems to be done to value this effort after the event.

Facebook has a whole section of their developer website dedicated to curated videos: https://developers.facebook.com/videos/

**Comment by markknol** [comment]
That is actually a good point! 
We could setup something like this (quickly created in devtools)

![image](https://user-images.githubusercontent.com/576184/34875621-55dfa596-f79e-11e7-8295-4794792b41a1.png)


![image](https://user-images.githubusercontent.com/576184/34875605-43ba7256-f79e-11e7-8647-05abf6e01627.png)

**Comment by elsassph** [comment]
Looks good, though each video needs a title and description.

It's important to curate and avoid outdated material.
