### ISSUE TITLE
Community forum is offline

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/haxe.org#293]
As of this writing, I can't access it and `traceroute` returns `Unknown host`.

**Comment by ibilon** [comment]
We've had hosting issues.
So now community.haxe.org points to the new host (may need to wait for dns propagation), but we still need to finish the migration, so there's no content yet.

**Comment by markknol** [comment]
Whats the status now?

**Comment by fullofcaffeine** [comment]
Still down:
https://www.dropbox.com/s/lu5u2jy8i8iyfgf/Screenshot%202018-01-28%2013.05.37.png?dl=0

**Comment by markknol** [comment]
Yes I can see myself that it is down :)

I was mostly wondering about the server/mirgation part.

**Comment by ibilon** [comment]
Everything should be working now.
