### ISSUE TITLE
serialization/format page missing

### ISSUE THREAD

**Issue by intoxopox** [HaxeFoundation/haxe.org#295]
http://haxe.org/manual/serialization/format is not available.

**Comment by intoxopox** [comment]
Correct page is here: http://haxe.org/manual/std-serialization-format.html

**Comment by markknol** [comment]
Where did you find this link?

**Comment by intoxopox** [comment]
I think I posted the issue on the wrong repo. Meant to post it on api.haxe.org. On https://api.haxe.org/haxe/Serializer.html, there is an incorrect link to the serialization format specification that points to https://haxe.org/manual/serialization/format. It should point to https://haxe.org/manual/std-serialization-format.html. The same incorrect link is also on https://api.haxe.org/haxe/Unserializer.html.

**Comment by markknol** [comment]
Thanks! I've updated the link in the API documentation and added a redirect to make it work on older api pages online.
