### ISSUE TITLE
Add link to merchandise shop

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#297]
* [ ] Make shop.haxe.org and redirect to https://shop.spreadshirt.nl/haxe/
* [ ] Make shop look more Haxe branded
* [ ] Add link to shop somewhere on website

**Comment by markknol** [comment]
@andyli can add this subdomain + make this redirection

**Comment by andyli** [comment]
@damoebius Does spreadshirt support CNAME? It should have mentioned something about how to use a custom domain. Doing redirection doesn't look as good.

**Comment by damoebius** [comment]
https://www.spreadshirt.com/blog/2007/02/16/domain-name-tutorial/
could be shop.haxe.org

**Comment by andyli** [comment]
I also found the link you mentioned, but that just suggests using redirection (in 2 different ways). If custom domain is properly supported by spreadshirt, there should be some setting and instruction in the setting page (where you configure the shop name, the display currency etc).

**Comment by andyli** [comment]
I've just registered an account. Looks like it doesn't support custom domain, but just web embedding. That is, we create a webpage, then use its JS code to embed the shop into the webpage.

The embed setting can be found at "sales channels" -> shop settings (the "edit" button) -> "advanced settings" -> "embed shop in website".

**Comment by damoebius** [comment]
Well, this is a thing i suggested. We can add an entry menu on haxe.org and embed the shop in a new page.

**Comment by damoebius** [comment]
@andyli @markknol ok to embed the shop in haxe.org ?

**Comment by markknol** [comment]
Yeah I'm fine with that.
I tried the snippet on its own, but doesnt seem to do much: http://haxe.stroep.nl/shop

**Comment by damoebius** [comment]
It's work : https://codepen.io/damoebius/pen/NyvmZe?editors=1010

**Comment by andyli** [comment]
I guess you don't need my help on dns. Please go ahead.

**Comment by damoebius** [comment]
Requirements :
[x] Display US Shop in English and $
[x] Display EU Shop in English and €
[x] Display Shop selection popin 
[x] Remenber country choice 
[x] Mobile Display support

Optionnals :
[ ] Add Shop selection buttons to switch

**Comment by markknol** [comment]
Shop is live
