### ISSUE TITLE
community logo 1 px off

### ISSUE THREAD

**Issue by MatthijsKamstra** [HaxeFoundation/haxe.org#299]
I am not sure if this is the correct place to mention this.

<img width="358" alt="screen shot 2018-02-16 at 09 55 48" src="https://user-images.githubusercontent.com/907219/36300043-ed1f4ed0-12ff-11e8-9f5b-683a08fd4bd7.png">

as you can see the image is 1px off on Google Chrome osx

this is absolutely not a better solution (change `line-height: 22px;` into `21px`)

```
.brand.sub {
    background: linear-gradient(to bottom, #39332d 50%, #2c2722 51%);
    padding: 14px 20px 14px 20px;
    margin: 0 10px 0 0;
    font: bold 18px "arial black", "open sans";
    line-height: 21px; 
    color: #fff;
}
```

but it does fix it quick and dirty

**Comment by ibilon** [comment]
Should be good now.

**Comment by MatthijsKamstra** [comment]
and it is beautiful !!
