### ISSUE TITLE
New partner

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#306]
Blue Mammoth Games is a new HF Supporter, here's the logo to add with link http://www.bluemammoth.com/

![bmglogosimple](https://user-images.githubusercontent.com/1022912/36632111-5f6c7d7c-1982-11e8-811c-aa3384bd7588.png)

**Comment by nadako** [comment]
What would be super-awesome is a couple words about how our partners use/are planning to use Haxe. I.e. for me as a contributor this would be motivational

**Comment by ncannasse** [comment]
That's something our upcoming marketing manager will be doing I guess ;)
