### ISSUE TITLE
Code Highlighting edgecases

### ISSUE THREAD

**Issue by markknol** [HaxeFoundation/haxe.org#315]
* [x] XML also gets highlighted as if it is Haxe code.  https://haxe.org/manual/cr-completion-field-access.html 
* [x] Homepage doesn't have highlighting anymore
* [x] Changelog doesnt have highlighting anymore https://haxe.org/download/version/4.0.0-preview.3/
* [x] We can remove old styles related to the highlighting
* [x] I know this is personal, but I dislike this gold/brownish color, can we change that to something else? Maybe just dark gray #333?
   ![image](https://user-images.githubusercontent.com/576184/38486535-a2da5bc4-3bdd-11e8-893c-8f5de4e2a2d1.png)

**Comment by markknol** [comment]
Ill change the colorscheme on VSCode buildin theme and come back to you 😛

**Comment by ibilon** [comment]
All done.

For the XML, it is correctly highlighted, the issue is that the manual sets all code blocks as haxe code.
I'll fix that.

Still missing js and shell grammars, maybe a couple others for the manual.

**Comment by ibilon** [comment]
Blocks now have their correct language with https://github.com/HaxeFoundation/HaxeManual/commit/29133cc9816ca6e63da4e11e99a79856aecd1be5.

Grammars missing:
* js
* sh
* as3
* cpp

**Comment by markknol** [comment]
That's a nice solution for the haxe manual!
