### ISSUE TITLE
API docs pages are super-wide due to white-space:nowrap

### ISSUE THREAD

**Issue by jcward** [HaxeFoundation/haxe.org#322]
On the API docs there's a (new?) span at the top -- `label-meta-headerClassCode`

(huh, img won't paste here? guthub broken? :stuck_out_tongue:)

Screenshot: first image at https://imgur.com/a/GRUYHyb

You'll also noitice that the page horizontal scroller indicates the page is probably ~5000px wide.

I'm not sure what the intended behavior is / was, but that purple span has a `white-space:nowrap` css rule inherited from .label

I presume it's not supposed to contain this much content? (See second image at: https://imgur.com/a/GRUYHyb)

**Comment by Gama11** [comment]
Dox hides some metadata via a blacklist (thoes metas which are just implementation details like this one), but it's just not the right approach IMO.. some things like this are always gonna slip through. And even the list was complete, new meta will be added. I think a whitelist would be better / safer (cc @markknol).

**Comment by ibilon** [comment]
Fixed by https://github.com/HaxeFoundation/dox/commit/f752d4a5a2e4e33252207186fa3de18bfc63d396.
