### ISSUE TITLE
Unreference old.haxe.org

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#331]
Something for some searches Google is still giving me old.haxe.org as top search result. Maybe we should add some kind of robots.txt to unreference it ? not sure what's the right technical way to do it.
We might still want to keep the website online, although it's rarely used.

**Comment by Merelleya** [comment]
You can set the robots meta tag to noindex. That will remove the pages from
the search results.

If there are newer versions of the pages, you could map those and use the
attribute canonical to indicate that the old page is a duplicate. This
would require more detailed looking into it, though.

**Comment by Simn** [comment]
IMO the fix here should be to make sure all the content from old.haxe is also available on current.haxe. It also prioritizes correctly, there are just some things missing.

**Comment by markknol** [comment]
@ncannasse can you give examples when old.haxe appears? 

I agree with Simn, all relevant content should be in new docs.  I'm not sure what's missing. Some old stuff might be still relevant for Haxe 2 users (like this one http://old.haxe.org/manual/haxe3/migration), removing from search engine would make it harder for people to look that up.

**Comment by Merelleya** [comment]
I agree, all the relevant content should be moved.

However, the duplicate stuff should then be de-indexed and/or removed both
for ranking purposes and clarity. The "some old stuff" should be looked at
and it should be decided if it is to be kept or delted. If it is to be
kept, it should be moved somewhere sensible.

It is a lot of work, but tidying up has to be done ^-^.

**Comment by ibilon** [comment]
Sorry meant to close https://github.com/HaxeFoundation/HaxeManual/issues/331

**Comment by bubblebenj** [comment]
Maybe it could be possible to add a note to every page of old.haxe.org saying something like:
"If not haxe 2 related, this content should be available on the current haxe site.
If not then please fill an issue in the haxe.org github https://github.com/HaxeFoundation/haxe.org/issues/ or better propose a pull request to add it".

**Comment by ibilon** [comment]
I removed the last reference to old.haxe.org from the blog, I can't find anything in the manual or api doc.
The only thing I could find is a comment in the php generator: https://github.com/HaxeFoundation/haxe/blob/development/src/generators/genphp7.ml#L748.
Also the old website isn't working anymore.
So it should be safe to say google won't recommend it anymore.
