### ISSUE TITLE
Markdown tables are squashed

### ISSUE THREAD

**Issue by caspervonb** [HaxeFoundation/haxe.org#333]
[The table on this page](https://haxe.org/documentation/introduction/compiler-targets.html) was probably intended to be full width, I have a vague memory of a few more but that's the one I could find now.

![screenshot from 2018-06-26 05-33-09](https://user-images.githubusercontent.com/157787/41877046-78a7604c-7902-11e8-96cc-2c110529a814.png)

**Comment by markknol** [comment]
Thanks for reporting!
