### ISSUE TITLE
curd application using  haxe 

### ISSUE THREAD

**Issue by shyamkumar123** [HaxeFoundation/haxe.org#334]
This is not an issue with the haxe website. I'm not even sure what is being asked. If you'd like to know how to make a crud application with Haxe then the forums would be a better place to ask for help.

**Comment by shyamkumar123** [comment]
please give me solution on that ASAP.

**Comment by shyamkumar123** [comment]
Could u please suggest me how to develop curd app using haxe

**Comment by markknol** [comment]
Please use community.haxe.org
