### ISSUE TITLE
Can't read about reflection

### ISSUE THREAD

**Issue by mogwaipoet** [HaxeFoundation/haxe.org#340]

**Comment by ibilon** [comment]
What is the issue exactly?
There is a page about reflection in the manual https://haxe.org/manual/std-reflection.html

**Comment by mogwaipoet** [comment]
Sorry about the confusion, I thought more information was automatically included in the issue.

Would it be possible to set up a redirect from https://haxe.org/api/reflect? There are external links pointing to it.

**Comment by markknol** [comment]
I've updated. Can you link me to the source of that article?

**Comment by ibilon** [comment]
When you do a search for `site:old.haxe.org` on google you'll find loads of those urls, which have potentially website linking to them.

**Comment by markknol** [comment]
yeah I picked some of them: reflect,array,date,sys,type,map,int,math,dynamic,enum,float,class,xml
If anyone wants to spend more time on this, be my guest 👍
