### ISSUE TITLE
broken link on Use Cases > desktop for HaxeUI getting started

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/haxe.org#341]
On <https://haxe.org/use-cases/desktop/> the link to the Article "Getting started with HaxeUI." appears to no longer work. I just get a "Cannot GET /getting_started.jsp" blank page.

**Comment by uvtc** [comment]
I don't know what the correct link should be. In fact, I can't find a getting-started or tutorial doc anywhere on the haxeui site.

**Comment by andyli** [comment]
@ianharrigan Do you have an updated getting started page?

**Comment by ianharrigan** [comment]
Hi,

There is this: http://haxeui.org/guide/start.html, but its incomplete. I wonder if it just makes more sense to link to the main page for now? 

Cheers,
Ian

**Comment by markknol** [comment]
@ianharrigan Why isn't this page/guide linked on your homepage? Can't find any links to that?
