### ISSUE TITLE
Area for menagerie of getting-started tutorials?

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/haxe.org#347]
I think it would be very useful to start a collection of short target-specific getting-started tutorials that could be linked to from under the "Learn Haxe" heading at haxe.org . One directory (and possibly one markdown file) per tutorial --- a directory, since into which you might need a place for screenshot images if present.

I'm thinking specifically about three types of tutorials:

 1. how to make and run a hello-world program for a given target language/platform (these will likely be quite short)
 2. how to add your own Haxe code (and lib from Haxelib) to an existing hello-world app already written in ${target language} or for ${target platform}
 3. how to use existing ${target language/platform} modules within your own hello-world Haxe program

The purpose of the first of the three above is to cause the reader blink a few times and say out loud to no one in particular, "Oh. That's no trouble at all. Nice!". :)

As for the other two types of tuts outlined above, two great strengths of Haxe appear to be:

  * the ability to incorporate your own high-quality type-checked beautiful Haxe code into some other existing non-Haxe project, and
  * the abliity to leverage 3rd-party non-Haxe code libraries by including them into your own Haxe project.

I think it's vital (particularly for a universal language with a multitude of output targets) to show users right off the bat how those things can be done.

Incidentally, questions which could be answered by these types of short tutorials are asked every so often. [There was just one today, in fact](https://community.haxe.org/t/haxe-microservice-with-java-target/1144).

Some comments:

  * I realize that this is the sort of thing that often goes into a wiki, but I think using a repo of markdown files, with PR's, works far better than a wiki (for many reasons, which I can supply at the slightest prodding, at the merest whiff of curiosity from you! :) )

  * This is different from the code cookbook, which I think is more language-focused. This would be more of a "menagerie of getting-started tutorials".

  * There may end up being more than one getting-started tutorial per target, given the variations in how some of the different targets/platforms handle projects, modules, etc.

  * There may end up being more than one tutorial per target/platform due to one being for GNU/Linux, another for MS Windows, another for Mac OS X... (Unfortunately the term "platform" is overloaded here: the Haxe compiler can target different platforms (such as Hashlink, the JVM, etc.), but can also itself *run* on different platforms (such as GNU/Linux, Mac, and Windows) Not sure the best way to disambiguate those.).

  * I think that IDE-specific and framework-specific tutorials *probably* belong on their own respective sites, however, it may be useful to include some if the parts are tricky to all get configured together. For example, "How to use Vue.js, in your Haxe project, a project which is managed within Intellij and is using the IntelliJ Haxe plug-in".

  * I'll probably start writing some of these as I learn more Haxe (even if only for my own notes), but they'll be limited in scope (I may only use a few of the output targets), and also, I unfortunately won't have much (if any) free time for at least a few weeks.

  * I think these should be separate from the Haxe Manual. Because:

      * they're more standalone (and some will probably include screenshots),
      * they're not strictly about the Haxe language itself,
      * they're necessarily a little more messy (relying on other tools) and/or more messily organized,
      * and because, aside, I'd also like to at some point convert the Haxe Manual to markdown files, but that's a little more up-front labor-intensive (unable to work on right now) and the topic of another issue/PR.

My questions:

  * What do you think?
  * Perhaps the Manual's "Target Details" sections could be pulled out and become separate articles in the target-specific tutorials? Would that be a desirable simplification of the manual?
  * Should these tutorials go into this HaxeFoundation/haxe.org repo, or into its own separate repo, or even maybe my own repo which can then be transferred over to the HaxeFoundation org if that works better?

Thanks!

**Comment by ncannasse** [comment]
I think that would be extremely valuable. I'm all for more documentation on how to integrate and better interact (call-in/out) between Haxe and native platforms.

Also, writing these examples we might found that the current ways to interact with the native platform on some target could be improved with some additional compiler support.

**Comment by uvtc** [comment]
Ok. I'll start doing some explorations and writing some docs and see how what I get. Thanks.

**Comment by uvtc** [comment]
Created https://github.com/uvtc/haxe-getting-started-tutorials
