### ISSUE TITLE
Contribution tips.

### ISSUE THREAD

**Issue by nadako** [HaxeFoundation/haxe.org#35]
I think we lack a good page on how one can contribute to Haxe, or at least I didn't find one.

I believe it deserves an individual menu item that links to a page listing what can be done i.e.
* Report issues (a link to https://github.com/HaxeFoundation/haxe/issues, short description on how to create useful issues)
* Fix existing issues and contribute new code. We currently have a short "buildiing instructions" page, however it doesn't describe stuff like Neko installation and `HAXEPATH`/`HAXE_STD_PATH` env variables. A short intro into both OCaml and Haxe code structure would help a lot as well.
* Write documentation for the code (some style guide would be nice).
* Write content for the site ("contribute here" links are awesome, also need some info on how to add a new page).
* Mention "satellite" projects that could use some love, i.e. haxelib, hxcpp, hxcs, hxjava.
* Anything I forgot?

**Comment by Antoine-Lassauzay** [comment]
Some good ideas in there : https://github.com/pengwynn/flint

**Comment by Simn** [comment]
I've written a short filing-issues overview here: https://github.com/HaxeFoundation/haxe/wiki/Filing-Issues-checklist

**Comment by markknol** [comment]
@Simn. Wouldnt it be an idea to put that wiki content (also) into a CONTIBUTING.md file? This is picked up [like this](https://github.com/pengwynn/flint/issues/new) (see tooltip message)

**Comment by Simn** [comment]
Oh nice, I wasn't aware of that.

**Comment by nadako** [comment]
How nice! Good idea!

**Comment by markknol** [comment]
It's in https://github.com/HaxeFoundation/haxe/pull/3918

**Comment by Merelleya** [comment]
Is this sorted now or are we still in progress?

**Comment by Simn** [comment]
It's good enough. Not like anyone reads these things but at least we tried.
