### ISSUE TITLE
Partners

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#354]
Here's some changes for the partners list:

* [x] please move Motion-Twin from Strategic to Supporters
* [x] please added Spiele Palast (logo below) as Strategic Partner -- https://www.spiele-palast.de/
* [x] please rename "Strategic" Partners category to "Enterprise" Partners (new keyword for supports plans)

Thank you :)

![logo_spiele-palast_600x200](https://user-images.githubusercontent.com/1022912/51250668-63679680-1997-11e9-8bca-7f2c1b0f24c1.png)

**Comment by ibilon** [comment]
Should `Haxe Foundation Supporters` be changed to `Professional Partners` or is that something different?

**Comment by ncannasse** [comment]
@ibilon yes please
