### ISSUE TITLE
Node-Webkit -> NW.js

### ISSUE THREAD

**Issue by TheJaredWilcurt** [HaxeFoundation/haxe.org#356]
Node-Webkit was rebranded to NW.js several years ago. It has also since undergone some architectural changes that affected the API.

If Haxe has not updated it's NW.js integration since the days of Node-Webkit, then it will be pretty out of date. These API changes are documented here:

* http://docs.nwjs.io/en/latest/For%20Users/Migration/From%200.12%20to%200.13/

**Comment by markknol** [comment]
Thanks for letting know. I'm not sure how accurate the definition files/extern library is, but at least I changed the name on the website.

**Comment by Gama11** [comment]
Hm, considering it was last updated 4 years ago... :)
