### ISSUE TITLE
"What they say about haxe"

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/haxe.org#36]
A page on haxe.org listing various tweets about people who had a nice experience with Haxe, using tweeter widget. One example:
https://twitter.com/sashmackinnon/status/471411076211294208

It's like a lot of quotes in various contexts, but feel more "real"

**Comment by Merelleya** [comment]
Ok, so what about this topic? 

Maybe we should revamp this into testimonials and then get some statements from people who have worked with haxe. We can also dig out the Tweets and quote them. 

Another idea would be a project feature page where we can feature projects that were realized with haxe, plus a short article/interview and some statements. (a little more feature like than the use-cases).

Or, we decide to close this for now and revisit it when we have more concrete plans.

**Comment by ncannasse** [comment]
After looking at it, they are not much in line with the professional aspect of the current haxe.org, so droping the idea for now. If we want to do something about it, more in-depth testimonials/interviews (magazine format) would be a lot better.
