### ISSUE TITLE
OS X build instructions

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#363]
I just tried following the OS X build instructions here: https://haxe.org/documentation/introduction/building-haxe.html

They seem to be a bit outdated because they don't mention our opam dependencies at all, leading to errors about ocamlfind when trying to `make` stuff.

**Comment by andyli** [comment]
The updated instruction is in https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md. We should just update the page and point ppl to read `extra/BUILDING.md`.

The reason of having the instruction in the source folder is that the instruction changes version by version.

Also, it's better to have the instruction included with the source. Think what if buying a box of LEGO and it tells you to visit a web page for the assemble instruction...

**Comment by Simn** [comment]
Makes sense to me!

**Comment by ibilon** [comment]
Done in https://github.com/HaxeFoundation/haxe.org/commit/c4dd6876e42ab371e95bc64f0c7c423c185aa862.
