### ISSUE TITLE
link to HashLink?

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/haxe.org#386]
Looking at haxe.org, I'm unable to find a link to [HashLink](https://hashlink.haxe.org/). Am I missing it?

Clicking on the icons for all the target platforms takes me to https://haxe.org/documentation/introduction/compiler-targets.html but there's no link to the HashLink site there.

The toolkit intro page https://haxe.org/documentation/introduction/toolkit-introduction.html talks about target platforms ... maybe it should contain a link to the compiler-targets page.

Also, if it's a HaxeFoundation-supported project, it would belong here https://haxe.org/foundation/supported-projects.html as well, correct?

Thanks.

**Comment by markknol** [comment]
Good one, I made some links to it.
