### ISSUE TITLE
"Building Haxe from source" page should be removed

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/haxe.org#388]
@nadako and @Simn agreed that the version in the repo should be the only source.

https://github.com/HaxeFoundation/haxe/blob/development/extra/BUILDING.md

Not sure if the haxe.org page is linked to from anywhere.

**Comment by andyli** [comment]
I've already added a note about referring to the repo in https://github.com/HaxeFoundation/haxe.org/commit/6d3325555e6349f0c3d23c708dfad81249c237ec.
I didn't remove the page as it may be still useful for people looking into building Haxe 3.x, but feel free to remove/tweak if that's not clear enough.
