### ISSUE TITLE
Target list should be updated

### ISSUE THREAD

**Issue by Aurel300** [HaxeFoundation/haxe.org#394]
https://haxe.org/documentation/introduction/compiler-targets.html

PHP 7 is now the only PHP we support, we should add a "discontinued" note to the PHP row and rename the target to PHP 5. I'm guessing AS3.0 will soon have a similar note.

There are also more details we could put in the table:

 - supports threading?
 - can it be debugged and stepped through nicely?
 - UTF-16?

**Comment by Gama11** [comment]
Also, JVM.

**Comment by Gama11** [comment]
And maybe Eval deserves a mention too?

**Comment by markknol** [comment]
Maybe we should merge this one in there too https://github.com/HaxeFoundation/haxe#version-compatibility

**Comment by ibilon** [comment]
Fixed by https://github.com/HaxeFoundation/haxe.org/pull/408.
