### ISSUE TITLE
Content for the "Desktop Apps" use case

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#4]
If you have any content for the "desktop apps" use case page, please leave a comment here.

We are looking for:
- **Testimonials / Quotes**:  If you have used haxe for creating desktop apps and it has been awesome, leave a short 1 sentence quote, with your name, company and URL.
- **Showcase**: If you have an app you would like included in the showcase, please include the name of your app, an image for the carousel, and a 1 line description.
- **Popular Libraries**: If there's a library that is used by a large number of Haxe app developers and we've left it out, let us know.
- **Tutorials**: if you have a tutorial, please supply a link, a title, and a 1 line description.

Please note we are not going to guarantee that items posted here will be included.  

Once we have enough content we can close this issue.

**Comment by fullofcaffeine** [comment]
You might add Atom to the list, besides NotWebKit. Franco has externs for it - https://github.com/fponticelli/hxatom-shell.

**Comment by Simn** [comment]
Are you sure you got the right issue?

**Comment by fullofcaffeine** [comment]
Ops, my apologies if it's not the right issue. I clicked the link from the website. I now see it was supposed to be for articles, only.

**Comment by ibilon** [comment]
The uses cases have enough content, let's close this issue and open a new one on a case by case basis.
