### ISSUE TITLE
lib.haxe.org outdated command

### ISSUE THREAD

**Issue by patrickgh3** [HaxeFoundation/haxe.org#402]
This page: https://lib.haxe.org/documentation/haxelibs-in-projects/ has an outdated command syntax. It has "--main", "--library", and "--js", when they are now "-main", "-lib"- and "-js". As someone new to Haxe this was confusing and made me have to do a lot more searching. Additionally, I would submit a pull request, but I don't see a way to do so for lib.haxe.org, only haxe.org. Thanks for your time.

**Comment by Gama11** [comment]
It's the opposite - they're not outdated, they're the new Haxe 4 style CLI arguments.

**Comment by patrickgh3** [comment]
Ahh, I see. Thanks for the quick reply. I'd like to request that be noted on the page, since right now Haxe 3 is the default on https://haxe.org/download/.

**Comment by ibilon** [comment]
Haxe 4 has been released now.
