### ISSUE TITLE
Github automation for Haxe website

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#41]
I'd like to work on this over the weekend, but have a few questions re: strategy.

With the manual, we have a Github hook set up so any "push" event will get the site to pull down the latest markdown content, convert it to HTML, and keep a copy for any requests to `/manual/*`

For the site, I do not want to fully automate this, as we have a mix of content and code/design - sometimes we may want to merge a pull request but preview it before going live.

I propose:

* Having two branches, "master" and "staging".
* Any pull requests which are simple content changes go to "master"
* Any pull requests which involve changing code or stylesheets go to "staging"
* Github links "master" with the live site, so a push/merge on master will trigger an update of the live site.
* Github links "staging" with `staging.haxe.org` (or similar) and we can preview changes there after a push/merge to the staging branch.
* If we like what we see on staging, we merge into master.

Does this sound like an acceptable workflow?

cc @ncannasse @Simn

**Comment by Simn** [comment]
Let's not make this too complicated. I figured out how to run the website locally so I don't think a separate staging branch is necessary.

**Comment by jasononeil** [comment]
This is actually done already.  A commit to master gets built and deployed
from Travis.

**Comment by Simn** [comment]
Aaah awesome! Thanks a lot for this, now it's much more fun to actually change something. :)

**Comment by jasononeil** [comment]
No worries, I got it working about a couple of weeks ago but wanted to see
how it performed with accepting pull requests etc before making any noise
about it.

It seems to be fine:

https://travis-ci.org/HaxeFoundation/haxe.org

**Comment by Simn** [comment]
@jasononeil: I just checked the deployment through travis, it's really nice!

Do you think you could help getting the same done for our API docs? Our travis already builds a .zip from with the latest documentation here: https://travis-ci.org/HaxeFoundation/haxe/jobs/52106094#L618

The idea is to automatically sync that to http://api.haxe.org/v/dev/ so we always have the latest documentation there. I was briefly talking with @andyli about it but never got around to figuring out how to setup the SSH access properly.

**Comment by jasononeil** [comment]
Yeah for sure - can you create a new issue and assign it to me?

Basically the process will be:

   - Generate a RSA key, and encrypt it in a way that Travis can decrypt.
   I followed the instructions here:


   http://pghalliday.com/github/ssh/travis-ci/2014/09/19/auto-build-and-deploy-github-pages-with-travis-ci.html

   though I think I simplified it a little bit.

   - Make sure that key is in the "authorized_keys" on the haxe.org server
   for a user that has permission to write to that directory.


   - In Travis, add something like:

   scp bin/api.zip user@haxe.org/data/api-dir/api.zip
   ssh user@haxe.org "linux command to unzip to the right location"

It will be great to have the dev version be that current.

**Comment by markknol** [comment]
Maybe if we are doing such stuff, it can also install a latest haxe version for try.haxe so we can test code on the latest dev and release version?

**Comment by jasononeil** [comment]
@markknol I would love to see that.  Especially if you could test a piece of code and show that it works on one version but not on another version.  

I don't know much about the try.haxe infrastructure though... if you know how to run two versions side by side (in different directories or subdomains) I could help with the Travis / SSH deployment stuff.
