### ISSUE TITLE
Use-case suggestion

### ISSUE THREAD

**Issue by RMax2015** [HaxeFoundation/haxe.org#411]
From https://haxe.org/use-cases/desktop/
Here is a Desktop/Laptop/Tablet? use case:
forGL is a free application written in Haxe to help learn computer programming.

Input format of forGL is a very simplified form of a Natural Language.
Nouns, Verbs, Operators (like Math), and Punctuation make up the parts of speech.
European languages are supported now with support for others soon.

forGL itself builds to C++, Java, Python, C#, JavaScript.

When export feature is working better, Haxe source file(s) will be generated as wanted.

Because a Dictionary metaphor (and also actual Implementation!) is used, words may be used from any language that has a written form that can be parsed/interpreted.  Goal is to support 100+ major languages now in use and various others.  Left to Right reading order is working for European languages now.

Please see   forGL.org   site for many more details.

**Comment by ibilon** [comment]
Do you have a demo of an application done with forGL? Couldn't find one.

**Comment by RMax2015** [comment]
There is no exact demo of a built app. Export as Code (to Haxe) is not
complete. The test_factorial Verb when it runs gives an example of a simple
app that can be done by retyping the screen of Export into your own source
code.

**Comment by ibilon** [comment]
Then it's a little too soon to be added as a use case, since it's meant for people looking for technology that they can use to complete their projects.

I'll close this issue for now until your project is more complete.
