### ISSUE TITLE
try.haxe.org still running Haxe 3.4.4

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/haxe.org#424]
I just wondered about some compiler errors while testing out some things on https://try.haxe.org when I realized it is running on Haxe 3.4.4 from 2017.

Is there any chance you can upgrade this to Haxe 4.0.5?

**Comment by tynrare** [comment]
This is another repo https://github.com/clemos/try-haxe

**Comment by sebthom** [comment]
Solved as of https://community.haxe.org/t/try-the-new-try-haxe/2921

Thanks guys!
