### ISSUE TITLE
Not obvious where to find release notes and changelog

### ISSUE THREAD

**Issue by uvtc** [HaxeFoundation/haxe.org#427]
Every time a new release comes out I go looking for the release notes and changelog and realize I've forgotten where they are. Even when the post on the forum says, "It is available along with the changelog at https://haxe.org/download", my eyes miss it as soon as I see that big beautiful download graphic that dominates the Download page.

In fact, for the longest time I thought they were *only* located on the page you're taken to *after* downloading.

To make it easier to find those 2 docs, I think the text on the Downloads page should be changed from:

> Thank you for choosing Haxe!
> Download for your platform and start developing today.

to

> Thank you for choosing Haxe!
>
> \[Scroll Down\] for the Release Notes and Changelog, or
> download for your platform and start developing today.

(Note the blank line added as well.)

**Comment by Simn** [comment]
I appreciate the suggestion but this seems really unnecessary. There's a rather good chance that you're the only one who had this problem.

**Comment by uvtc** [comment]
Ok, thanks.
