### ISSUE TITLE
haxe unicode manual - page not found 

### ISSUE THREAD

**Issue by simonRiep** [HaxeFoundation/haxe.org#442]
As https://api.haxe.org/haxe/Utf8.html is Deprecated: "haxe.Utf8 is deprecated. Use UnicodeString instead."

https://api.haxe.org/UnicodeString.html 
has links to the manual for unciode at: https://haxe.org/manual/std-UnicodeString.html
but the page is not found.

**Comment by tobil4sk** [comment]
Current page is https://haxe.org/manual/std-String-unicode.html. This was fixed in https://github.com/HaxeFoundation/haxe/commit/3004f1862d20280cd31ea0a95455a4e1da2aa326.

The next release of Haxe will have the correct link in the documentation.

**Comment by ibilon** [comment]
The api documention links to the correct page now.
