### ISSUE TITLE
TravisCI failure because of xenial and deadsnakes

### ISSUE THREAD

**Issue by andyli** [HaxeFoundation/haxe.org#449]
Re. https://github.com/deadsnakes/issues/issues/195

There are no more python3.7 packages for Xenial, since Xenial reached EOL.

We probably should move to Focal and GitHub Actions.

**Comment by tobil4sk** [comment]
The python issue was resolved in #443 and #444, but it would still be good to move to github actions.

**Comment by ibilon** [comment]
Travis ci was replaced by github action.
