### ISSUE TITLE
Link to Haxedevelop from editor and Ide overview is dead

### ISSUE THREAD

**Issue by Strepto** [HaxeFoundation/haxe.org#452]
Hi, thought you might want to know this. When I visit this link I get redirected to some domain-hosting site, and not a real website.

https://github.com/HaxeFoundation/haxe.org/blob/b1ae9b1165521048ba84321ca406494eb5967a1a/pages/documentation/introduction/editors-and-ides.html#L33

As this is the primary IDE mentioned on that page it might be worth updating. 

Keep up the good work :)

**Comment by ibilon** [comment]
The link was removed in https://github.com/HaxeFoundation/haxe.org/pull/455.
