### ISSUE TITLE
Editors and IDEs should be more prominent

### ISSUE THREAD

**Issue by frabbit** [HaxeFoundation/haxe.org#51]
`Documentation -> Introduction -> Editors and IDEs` is really hard to find, it should be either moved directly under Documentation or to a new section `tools` which could be added to the main navigation, see https://www.dartlang.org/ as an example.

**Comment by Simn** [comment]
I think this is fine as it is. It's not like IDEs are our strong point and while I don't suggest explicitly hiding information about them, I also don't think it makes much sense to make it more prominent.

**Comment by ncannasse** [comment]
Maybe we should promote a bit more IntelliJ plugin, I'll contact TiVo regarding this

**Comment by Simn** [comment]
They seemed a bit frustrated with it so we might want to hold back on that. I'm trying to provide some support for Boyan to fix some of the outstanding issues.
