### ISSUE TITLE
Content for the "CLI" use case

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#6]
If you have any content for the "command line apps" use case page, please leave a comment here.

We are looking for:
- **Testimonials / Quotes**:  If you have used haxe for creating command line apps and it has been awesome, leave a short 1 sentence quote, with your name, company and URL.
- **Showcase**: If you have an app/tool you would like included in the showcase, please include the name of your app/tool, an image for the carousel, and a 1 line description.
- **Popular Libraries**: If there's a library that is used by a large number of Haxe CLI developers and we've left it out, let us know.
- **Tutorials**: if you have a tutorial, please supply a link, a title, and a 1 line description.

Please note we are not going to guarantee that items posted here will be included.  

Once we have enough content we can close this issue.

**Comment by carlcalderon** [comment]
I made a small xargs-like program that I'd love feedback on. https://github.com/carlcalderon/bux

The CLI uses a getopt-style flaggning interface for ease of use. I have also found a few quirks that I would like to address regarding the (Sys) Input buffer, where is the correct forum for that?

Cheers

**Comment by ibilon** [comment]
The uses cases have enough content, let's close this issue and open a new one on a case by case basis.
