### ISSUE TITLE
Can replace some files off Google references..

### ISSUE THREAD

**Issue by Laosj** [HaxeFoundation/haxe.org#61]
Can replace some files off Google references, because every time you open a Web site very slow

Started a few days ago, our County has not open Google

![1](https://cloud.githubusercontent.com/assets/7479482/3296233/4aad8b2a-f5d6-11e3-9e0d-ad454792fccd.png)

**Comment by Simn** [comment]
Is this still an issue?

**Comment by jasononeil** [comment]
The files are still hosted on 3rd party servers, including Google.

I've started trying to fix it.  Moving the Google search script to the bottom is breaking stuff at the moment but I'm sure it's fixeable.

Currently I'm loading most of our assets (jQuery, Bootstrap, Fonts, Icons) from CDNs... should I just move them all onto our server in case the others start getting blocked too?

**Comment by ncannasse** [comment]
@jasononeil yes i've add similar issues with google CDN before that, better host them ourself

**Comment by markknol** [comment]
It is an idea to create a static.haxe.org and put all stuff there, to have the same static resources available across the websites (lib.haxe.org, api.haxe.org, haxe.org, try.haxe.org etc ..)
