### ISSUE TITLE
Content for the "Cross Platform APIs" use case

### ISSUE THREAD

**Issue by jasononeil** [HaxeFoundation/haxe.org#7]
If you have any content for the "cross platform APIs" use case page, please leave a comment here.

We are looking for:
- **Testimonials / Quotes**:  If you have used haxe for creating cross platform APIs and it has been awesome, leave a short 1 sentence quote, with your name, company and URL.
- **Showcase**: If you have an API example you would like included in the showcase, please include the name of your API, an image for the carousel, and a 1 line description.
- **Popular Libraries**: If there's a library that is used by a large number of Haxe app developers and we've left it out, let us know.
- **Tutorials**: if you have a tutorial, please supply a link, a title, and a 1 line description.

Please note we are not going to guarantee that items posted here will be included.  

Once we have enough content we can close this issue.

**Comment by ibilon** [comment]
The uses cases have enough content, let's close this issue and open a new one on a case by case basis.
