### ISSUE TITLE
API Documentation is not for the released version

### ISSUE THREAD

**Issue by explorigin** [HaxeFoundation/haxe.org#91]
I'm a newcomer to Haxe and was trying to create a JSGenerator to suit my needs but I found that some API elements listed on the website are not available in the released stable version of Haxe.  Namely:

 - JSGenApi.hasFeature() (does not exist in 3.1.3)
 - Context.defined() (does not exist in 3.1.3 but is actually Context.getDefines() in the haxe master branch)

**Comment by Simn** [comment]
Surely Context.defined is available in 3.1.3.

But yeah it's an issue for which we don't have a good solution.

**Comment by Simn** [comment]
Starting from 3.2 we'll do it like this:

api.haxe.org: latest stable
api.haxe.org/v/dev: latest development (whenever I feel like updating it)
api.haxe.org/v/3.2: specific version

**Comment by explorigin** [comment]
That's perfect.

**Comment by Simn** [comment]
The API documentation has been updated. There's no /v/3.2 yet because that's the current version. I suppose it's good enough to just create that once the next version is released.
