### ISSUE TITLE
Who is Who 

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/haxe.org#96]
Hi there,

I would like to add a "Who is Who" page to the website. The page should contain the names, photos and a brief description of responsibilities for the lead developers and target maintainers.

The idea is to show that there are actual people behind Haxe and the Foundation. It would look more professional and make it easier for new people to find their way around and relate to the product.

I would like to include:

@ncannasse 
@Simn 
@waneck 
@fponticelli
@aduros
@hughsando
@andyli 
@nadako 
@frabbit 
@jasononeil 

I would be grateful if you could review this and see whether you are ok with having your face and name on the website. Content-wise I wouldn't include anything personal, just what you role in the Haxe-System is. I will, of course, have you review your entry before it is published.

If you have more people to add, please let me know. If I don't hear from you, I'll contact individually to hash out the details and get your pictures. Even Simon agreed to a picture!

Cheers,

Fiene

**Comment by fponticelli** [comment]
For what is worth I don't mind making all of my info public :)

**Comment by ncannasse** [comment]
Fine with me, I agree it looks more professional if there's something like a whole team behind it ;)

**Comment by nadako** [comment]
Sounds good, now I only need to find a good picture of myself. :-P

**Comment by hughsando** [comment]
Fine with me - I should see if I can find an updated photo - that one is so
old I could use it on a dating site.

**Comment by jasononeil** [comment]
Good idea!

Are you imagining one page with everyone on it, or a page devoted to each person?  I can get started on a template for it if it helps :)

**Comment by Merelleya** [comment]
One page with everyone on it. Just one or two sentences per person (like "Caue Waneck - Caue maintains both the Java and C# targets and....") and a small picture will be enough. We can still do features on them if we feel it is necessary xD. For now, Short and concise will do.

**Comment by Simn** [comment]
I would just go for:

Picture
Name
Role

Where Role is something very short like "C# and Java targets", "Webmaster" or "The only person who doesn't like short lambdas". :)

**Comment by Merelleya** [comment]
Ok, can I please get your pictures? 

@ncannasse 
@Simn 
@waneck 
@fponticelli
@aduros
@hughsando
@andyli 
@nadako 
@frabbit 
@jasononeil

**Comment by fponticelli** [comment]
Here is mine.




Il giorno ven 13 mar 2015 alle ore 15:44 Josefiene Pertosa <
notifications@github.com> ha scritto:

**Comment by frabbit** [comment]
@Merelleya you can use this picture https://dl.dropboxusercontent.com/u/21847103/frabbit.jpg

**Comment by ncannasse** [comment]
Here's mine http://imgur.com/VezRLHT

**Comment by andyli** [comment]
Mine: https://en.gravatar.com/userimage/4167363/9f93993fd564f3a6a494a2faf984e9f8.jpg?size=400

**Comment by waneck** [comment]
I hope this size is enough: http://imgur.com/qheDJVT

**Comment by nadako** [comment]
this one should be good https://www.dropbox.com/s/wt6l8tkzvyk7tat/photo.jpg?dl=0

**Comment by hughsando** [comment]
Here is mine:
https://www.dropbox.com/s/vddgez66saw87i9/HughSanderson.jpg?dl=0
Hugh

On Sat, Mar 14, 2015 at 5:44 AM, Josefiene Pertosa <notifications@github.com

**Comment by Simn** [comment]
Are we gonna do anything with this? Having an overview of the involved people would be useful for the blog as well so we can link some names. It's always good to connect a name to a face, even if that face is Franco's.

**Comment by ibilon** [comment]
I can do a page for this today, I may miss some role on some people though.

**Comment by Simn** [comment]
That's fine, we can deal with the content. It's just about getting started with a new page that's the problem (for me anyway).

On that note, it would be super-duper-doubleplus-awesome if you could briefly document the steps to get a new page on haxe.org.

**Comment by ibilon** [comment]
For a "normal" page it's not that much work,
you create your md/html file in the right folder, add it to the sitemap.json, F5 and it's there.

**Comment by Simn** [comment]
I have added some role description. But now that I'm looking at it I think we should structure this a bit more and add the following information:

* Year when the person started contributing to Haxe: This shows that most people have been involved for years, which is good.
* Location: We're from all over the world and that always looks good.

This is the data, though I merely guessed some of the dates:

Name | since | where
--- | --- | --- 
Nicolas | 2005 | France
Simon | 2011 | Germany
Caue | 2010 | Brazil
Hugh | 2009 | Australia
Andy | 2011 | Hong Kong
Dan | 2013 | Russia
Bruno | 2011 | USA
Heinz | 2012 | Germany
Jason | 2012 | Australia
Franco | 2007 | USA

Now we only have to make that look nice.

**Comment by nadako** [comment]
I just found a similar page on Ruby on Rails website that's worth noting: http://rubyonrails.org/community/

**Comment by markknol** [comment]
We can use the github avatars combined with a flag and date in a circle, something like on the lib.haxe user page.

**Comment by ncannasse** [comment]
:+1:
