### ISSUE TITLE
Issues when building

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/haxe.org#97]
I tried to build the current version following the README instructions today, using current Haxe. First issue I came across was this:

```
C:\GitHub\haxe\lib/detox/1,0,0-rc,8/src/dtx/DOMNode.hx:175: characters 22-35 : Unmatched patterns: Document | ProcessingInstruction | DocType | Comment | CData | PCData | Element
```

This was easy enough to fix by adding `case _: null;`, but after that I ran into another issue:

```
C:\GitHub\haxe\lib/ufront-mvc/1,0,0-rc,12/src/ufront/api/UFApiContext.hx:51: characters 2-11 : Class not found : app.api.SiteApiProxy
src/Server.hx:15: lines 15-65 : Defined in this class
```

The file has some documentation on that error:

```
Please note, you will need to explicitly import the API so that the build macro runs and the proxy is generated.  Otherwise you
will get a "Class not found : my.app.MainApiClient" error.  So instead, do:

	import my.app.MainApi;
	...
	new my.app.MainApiClient(url, errorHandler);
```

However, the import is there in app/Api.hx. I tried adding one to Server.hx as well but that didn't change anything.

@jasononeil: Any pointers? Did you recently build haxe.org using latest Haxe? I want to make sure that we are not looking at a regression.

**Comment by Simn** [comment]
Argh, it works with 3.1.3.

**Comment by Simn** [comment]
I bisected the breaking Haxe commit to this: https://github.com/HaxeFoundation/haxe/commit/2dfa

I checked detox to find quite of a bit of places that use a pattern `try Context.getType() catch(e:Dynamic) {}`. This might actually be a case where we should fix the documentation, not the implementation.

@ncannasse: Any opinions?

**Comment by ncannasse** [comment]
I would surely avoid to have silent errors in Context.getType

**Comment by waneck** [comment]
I've also ran into problems because of that null already. Got one of those
dreadful Interp.Invalid_expr error

**Comment by Simn** [comment]
I have no idea what happened there. It was me who originally documented that so I was probably just being sloppy, and then thought it was defined like this.

Anyway, it's fixed.
