### ISSUE TITLE
Testimonial from Dan Hett Re: His Art Installation powered with Haxe

### ISSUE THREAD

**Issue by Merelleya** [HaxeFoundation/haxe.org#98]
I have received the following statement from Dan and we do have permission to quote him, I am just not sure where to put it.

"my whole public speaking deal at the moment is about rapid prototyping and experimentation and things haxe works really well for this the whole reason I chose haxe was that A) it's quick and B) we had no idea what platform we were going to be deploying on this could have ended up being an iPad app and i could still have used the same codebase which was very exciting, and let us get on with creating rather than agonising over technology"

Here is a link to his speech pitch for WWX. Its an exciting project!

https://groups.google.com/forum/#!topic/thaxe-force/wxgs3u4JL7E

**Comment by Merelleya** [comment]
To further elaborate, what the installation is about:

"Secondly, and this is bigger - I've been using Haxe as a base for a large scale installation project that I'm building for a gallery here in the UK. We're putting together a physical machine that will allow users to log into a website, send a message, and the message will be beautifully formatted and printed out in the gallery (and streamed on the site so you can see your message pop out when it's done). Additionally the machine has a giant moving animatronic pencil and pretty light patterns and all sorts of stuff, so it really creaks into life while it's "writing" your message. All powered by the magic of Haxe, for a number of uses - the desktop build, the web app, and the server-side script too. All working in harmony, coupled with some creative use of an arduino and a LOT of wood and paint!"

And here is a little video for parts of it:

https://twitter.com/danhett/status/569124561368834048

I think we should feature this once it's finished^^.

**Comment by Simn** [comment]
This is a very interesting project because it highlights several use-cases of Haxe at once (and sounds really cool in general to boot). That's the problem with our use-case grouping on haxe.org though: I wouldn't even know where to put it.

I think we should introduce our own showcase page where we go into detail for certain projects. Add some nice pictures or even a video and describe how Haxe helped with the project. This way we can keep the use-case pages as an overview and the showcase pages as material for further reading.

**Comment by ncannasse** [comment]
@Simn agreed, that's more like a "magazine" content, big picture, big typo, good feelings. We might want to have this, but we need someone to write it. @Merelleya is volunteering maybe ?

**Comment by Merelleya** [comment]
If I am not volunteering I don't know what I am doing ^^. Naw, seriously. I would love to have that section and thus, will do my utmost to write content for it. I like nice pictures and good feelings. Also I think it's important to have more visual content people can relate to. It also helps promotion, because we will not only be able to tell people why we are using Haxe, but also why other people have chosen it, so happy sunshine all around.

**Comment by jasononeil** [comment]
What if we add a "Features" or "Articles" or "Blog" section.  It allows putting in big pictures, highlighted quotes, etc.

The most recent one could be linked to on the front page, as I mentioned here: https://github.com/HaxeFoundation/haxe.org/issues/39#issuecomment-75865243

I think we would need at least one feature a month to avoid it looking stale.  @Merelleya maybe if we can discuss what writing / editing workflow will work for you, and how you would like the page laid out, I can work on the template.

**Comment by Merelleya** [comment]
I'll make an overall plan for both the website and the social media pages and then we can see how much we will need. I agree, there should be at least one feature a month, but it also depends on the kinds of projects available and how the people we want to feature cooperate. 

Layout-wise, the normal online magazine layout is one column, with pictures (stretching the whole or half column) and highlighted quotes (also either stretching the column or in a box on the right or left side). 

Similar to this:
http://superlevel.de/spiele/indie-spiele/kentucky-fried-zero-act-3/

or

http://superlevel.de/spiele/sega-mega-drivegenesis-collected-works/

It should be somewhat flexible, depending on whether you want quotes or not and how many pictures you have, etc and allow videos and a title picture.

**Comment by Merelleya** [comment]
General discussion moved to #101

**Comment by ibilon** [comment]
Now that there's a blog this could be a post,
it's a year old though.

**Comment by markknol** [comment]
@merelleya is this still a thing? Otherwise lets close the ticket.

**Comment by ibilon** [comment]
I guess that's too old now, and if not just add it to the blog ;)
